/**
 * CHAOS CONTROLLER — Case Transfer Package section builders.
 * Pure data functions producing ReportDocument-compatible section arrays
 * ({ heading, rows, paragraphs, bullets, empty }). No rendering or PDF logic
 * lives here — that all happens through ReportDocument + captureDocumentPDF.
 */

import { format, differenceInDays } from "date-fns";
import { LETTER_FIELD_MAP, LETTER_LABELS, LETTER_SENT_FIELD_MAP } from "@/lib/disputeStageLogic";
import { getRelevantLegislation } from "@/lib/legislationMapping";

const fmt = (d) => (d ? format(new Date(d), "d MMM yyyy") : null);

export function buildReadMeSections(caseItem, { matterStrength, currentStage, regulator, advocacyService }) {
  return [
    {
      heading: "About This Package",
      paragraphs: [
        `This is a complete case transfer package generated by Chaos Controller for "${caseItem.title}". It contains every document, letter, piece of evidence and record relating to this dispute, structured so it can be handed directly to a regulator, tribunal, solicitor or support service without needing Chaos Controller again.`,
      ],
    },
    {
      heading: "Case Details",
      rows: [
        { label: "Case Title", value: caseItem.title },
        { label: "Case Number", value: `CC-${String(caseItem.id).slice(0, 8).toUpperCase()}` },
        { label: "Client", value: caseItem.complainant_name },
        { label: "Organisation Complained About", value: caseItem.organisation_name },
        { label: "Matter Strength", value: `${matterStrength}%` },
        { label: "Current Stage", value: (currentStage || "").replace(/_/g, " ") },
        { label: "Assigned Regulator", value: regulator },
        { label: "Assigned Advocacy Service", value: advocacyService },
        { label: "Generated", value: format(new Date(), "d MMMM yyyy, h:mm a") },
      ],
    },
    {
      heading: "Folder Guide",
      bullets: [
        "01 Executive Summary — one-page overview of the whole matter",
        "02 Complete Case Report — full case detail, evidence, timeline, matter strength",
        "03 AI Case Analysis — full AI assessment (strengths, weaknesses, risks, recommendations)",
        "04 Timeline — every recorded event in chronological order",
        "05 Weekly Snapshot — most recent activity summary",
        "06 Deadlines — all deadlines, grouped by month and in chronological order",
        "07 Letters — all formal complaint/settlement/escalation letters",
        "08 Responses — organisation responses received via the app portal",
        "09 Evidence — indexed evidence files plus the original files",
        "10 Emails — email correspondence log",
        "11 Uploaded Documents — original uploaded files",
        "12 Notes — manual notes, retrospective entries and chronology",
        "13 Contacts — organisation, regulator and client contacts",
        "14 Reports — copies of the case and executive summary reports",
        "15 Audit Trail — record of actions taken on this case",
        "16 Solicitor Bundle — everything needed for a tribunal or solicitor in one folder",
        "17 Legislation — laws relevant to this specific case",
        "18 Statistics — case metrics and timing statistics",
      ],
    },
  ];
}

export function buildTimelineSections(caseItem, events) {
  const derived = [];
  const push = (date, label) => { if (date) derived.push({ date: new Date(date), label }); };
  push(caseItem.created_date, "Case created");
  push(caseItem.first_complaint_sent_at, "1st Complaint Letter sent");
  push(caseItem.first_response_received_at, "Response received to 1st Complaint");
  push(caseItem.first_no_response_at, "No response recorded after 1st Complaint");
  push(caseItem.second_complaint_sent_at, "2nd Complaint Letter sent");
  push(caseItem.second_response_received_at, "Response received to 2nd Complaint");
  push(caseItem.second_no_response_at, "No response recorded after 2nd Complaint");
  push(caseItem.third_complaint_sent_at, "3rd/Final Complaint Letter sent");
  push(caseItem.third_response_received_at, "Response received to 3rd Complaint");
  push(caseItem.third_no_response_at, "No response recorded after 3rd Complaint");
  push(caseItem.accept_offer_sent_at, "Acceptance of Offer letter sent");
  push(caseItem.deny_offer_sent_at, "Rejection of Offer letter sent");
  push(caseItem.escalated_at, `Escalated to ${caseItem.escalation_body || "external body"}`);
  push(caseItem.final_outcome_at, "Final outcome recorded");

  const fromEvents = (events || []).map(ev => ({
    date: ev.event_date ? new Date(ev.event_date) : new Date(ev.created_date),
    label: `[${(ev.event_type || "event").replace(/_/g, " ").toUpperCase()}] ${ev.title}${ev.description ? " — " + ev.description : ""}`,
  }));

  const all = [...derived, ...fromEvents]
    .filter(e => e.date && !isNaN(e.date))
    .sort((a, b) => a.date - b.date);

  return [{
    heading: `Matter Timeline (${all.length} events)`,
    bullets: all.length ? all.map(e => `${format(e.date, "d MMM yyyy")} — ${e.label}`) : undefined,
    empty: "No timeline events recorded.",
  }];
}

export function buildWeeklySnapshotSections(caseItem, evidence, events, deadlines) {
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const twoWeeksAhead = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);
  const recent = (events || []).filter(e => e.event_date && new Date(e.event_date) > weekAgo);
  const upcoming = (deadlines || []).filter(d => d.deadline_date && new Date(d.deadline_date) > now && new Date(d.deadline_date) < twoWeeksAhead && d.status === "pending");
  const overdue = (deadlines || []).filter(d => d.deadline_date && new Date(d.deadline_date) < now && d.status === "pending");
  const lettersDone = Object.values(LETTER_FIELD_MAP).filter(f => caseItem[f]).length;

  return [
    {
      heading: "This Week",
      rows: [
        { label: "Status", value: (caseItem.status || "").replace(/_/g, " ").toUpperCase() },
        { label: "New Timeline Events", value: String(recent.length) },
        { label: "Upcoming Deadlines (14 days)", value: String(upcoming.length) },
        { label: "Overdue Items", value: String(overdue.length) },
        { label: "Letters Completed", value: `${lettersDone} of 6` },
        { label: "Evidence Files", value: String((evidence || []).length) },
      ],
    },
    {
      heading: "Recent Activity",
      bullets: recent.length ? recent.map(e => `${fmt(e.event_date)} — ${e.title}`) : undefined,
      empty: "No new activity in the last 7 days.",
    },
    {
      heading: "Upcoming Deadlines",
      bullets: upcoming.length ? upcoming.map(d => `${d.title} — Due ${fmt(d.deadline_date)}`) : undefined,
      empty: "No deadlines in the next 14 days.",
    },
    {
      heading: "Recommended Next Action",
      paragraphs: [
        !caseItem.first_complaint_sent_at
          ? "Send the 1st Complaint Letter to open the formal dispute."
          : overdue.length
            ? "Address overdue deadlines before proceeding further."
            : "Continue monitoring for a response and prepare the next letter in the sequence if the deadline passes.",
      ],
    },
  ];
}

export function buildDeadlinesSections(deadlines) {
  const now = new Date();
  const sorted = [...(deadlines || [])].sort((a, b) => new Date(a.deadline_date || 0) - new Date(b.deadline_date || 0));
  const byMonth = {};
  sorted.forEach(d => {
    const key = d.deadline_date ? format(new Date(d.deadline_date), "MMMM yyyy") : "No Date";
    byMonth[key] = byMonth[key] || [];
    byMonth[key].push(d);
  });
  const calendarSections = Object.entries(byMonth).map(([month, items]) => ({
    heading: month,
    bullets: items.map(d => `${fmt(d.deadline_date) || "No date"} — ${d.title} (${(d.status || "").toUpperCase()})`),
  }));
  const chronoSection = {
    heading: `Chronological Deadline List (${sorted.length})`,
    bullets: sorted.length ? sorted.map(d => {
      const daysLeft = d.deadline_date ? differenceInDays(new Date(d.deadline_date), now) : null;
      const urgency = daysLeft === null ? "" : daysLeft < 0 ? ` [OVERDUE ${Math.abs(daysLeft)}d]` : daysLeft === 0 ? " [DUE TODAY]" : ` [${daysLeft}d left]`;
      return `${d.title} — Due ${fmt(d.deadline_date) || "no date"}${urgency} — ${(d.deadline_type || "").replace(/_/g, " ")} — ${(d.status || "").toUpperCase()}`;
    }) : undefined,
    empty: "No deadlines recorded.",
  };
  return [
    { heading: "Deadlines Calendar", paragraphs: ["Grouped by month below, followed by a full chronological list."] },
    ...calendarSections,
    chronoSection,
  ];
}

export function buildMerchantResponsesSections(responses) {
  const sorted = [...(responses || [])].sort((a, b) => new Date(a.created_date) - new Date(b.created_date));
  return [{
    heading: `Merchant / Organisation Responses (${sorted.length})`,
    bullets: sorted.length ? sorted.map(r =>
      `${fmt(r.created_date)} — ${r.merchant_name || r.merchant_email} [${(r.response_type || "").replace(/_/g, " ")}]${r.offer_amount ? " — Offer: " + r.offer_amount : ""} — ${r.response_text}`
    ) : undefined,
    empty: "No responses received via the app portal.",
  }];
}

export function buildEvidenceIndexSections(evidence) {
  const sorted = [...(evidence || [])].sort((a, b) => new Date(a.event_date || a.created_date) - new Date(b.event_date || b.created_date));
  return [{
    heading: `Evidence Index (${sorted.length})`,
    bullets: sorted.length ? sorted.map((ev, i) =>
      `${i + 1}. ${ev.file_name} — ${(ev.file_type || "other").replace(/_/g, " ")} — ${fmt(ev.event_date) || "no date"}${ev.description ? " — " + ev.description : (ev.extracted_data?.document_summary ? " — " + ev.extracted_data.document_summary : "")}`
    ) : undefined,
    empty: "No evidence files uploaded.",
  }];
}

export function buildEmailCorrespondenceSections(emailLogs) {
  const sorted = [...(emailLogs || [])].sort((a, b) => new Date(a.created_date) - new Date(b.created_date));
  return [{
    heading: `Email Correspondence (${sorted.length})`,
    bullets: sorted.length ? sorted.map(e =>
      `${e.sent_at ? format(new Date(e.sent_at), "d MMM yyyy, h:mm a") : fmt(e.created_date)} — To: ${e.recipient_email} — "${e.subject}" — [${(e.status || "").toUpperCase()}]${e.attachment_names?.length ? " — Attachments: " + e.attachment_names.join(", ") : ""}`
    ) : undefined,
    empty: "No emails sent via the app.",
  }];
}

export function buildNotesSections(caseItem, events) {
  const noteEvents = (events || []).filter(e => /note/i.test(e.event_type || ""));
  const trackingNotes = Object.entries(caseItem.letter_tracking || {}).filter(([, v]) => v?.sentNotes).map(([k, v]) => `${LETTER_LABELS[k] || k}: ${v.sentNotes}`);
  return [
    { heading: "Case Notes", paragraphs: [caseItem.notes], empty: "No manual notes recorded." },
    { heading: "Retrospective Sent-Date Notes", bullets: trackingNotes.length ? trackingNotes : undefined, empty: "No retrospective notes recorded." },
    { heading: "Timeline Notes", bullets: noteEvents.length ? noteEvents.map(e => `${fmt(e.event_date)} — ${e.title}${e.description ? ": " + e.description : ""}`) : undefined, empty: "No dedicated note-type timeline events." },
  ];
}

export function buildContactsSections(caseItem, organisation) {
  return [
    {
      heading: "Organisation Complained About",
      rows: [
        { label: "Organisation", value: caseItem.organisation_name },
        { label: "Complaints Address", value: caseItem.organisation_complaints_address },
        { label: "Complaints Email", value: caseItem.organisation_complaints_email },
        { label: "Complaint Handler", value: caseItem.complaint_handler_name },
        { label: "Phone", value: organisation?.complaints_phone },
      ],
    },
    {
      heading: "Escalation / Regulator",
      rows: [{ label: "Assigned Regulator / Ombudsman", value: caseItem.escalation_body }],
      empty: "No regulator identified yet.",
    },
    {
      heading: "Client",
      rows: [
        { label: "Name", value: caseItem.complainant_name },
        { label: "Address", value: caseItem.complainant_address },
        { label: "Email", value: caseItem.complainant_email },
        { label: "Phone", value: caseItem.complainant_phone },
      ],
    },
  ];
}

export function buildAuditTrailSections(caseItem, evidence, events, emailLogs) {
  const entries = [];
  const push = (date, label) => { if (date) entries.push({ date: new Date(date), label }); };
  push(caseItem.created_date, "Case created");
  push(caseItem.updated_date, "Case last updated");
  (evidence || []).forEach(ev => push(ev.created_date, `Evidence uploaded: ${ev.file_name}`));
  (events || []).forEach(ev => push(ev.created_date, `Timeline event recorded: ${ev.title}`));
  Object.entries(LETTER_FIELD_MAP).forEach(([key, field]) => {
    const sentField = LETTER_SENT_FIELD_MAP[key];
    if (caseItem[sentField]) push(caseItem[sentField], `${LETTER_LABELS[key]} letter marked sent${caseItem.letter_tracking?.[key]?.manuallyMarkedSent ? " (retrospective entry)" : ""}`);
  });
  (emailLogs || []).forEach(e => push(e.sent_at || e.created_date, `Email sent: "${e.subject}" to ${e.recipient_email} [${e.status}]`));
  if (caseItem.escalated_at) push(caseItem.escalated_at, "Escalation unlocked / case escalated");

  const sorted = entries.filter(e => e.date && !isNaN(e.date)).sort((a, b) => a.date - b.date);
  return [{
    heading: `Audit Trail (${sorted.length} recorded actions)`,
    paragraphs: ["Derived from the case, evidence, timeline, letter and email records held by Chaos Controller. This reflects the timestamped records available for this case, not a dedicated system audit log."],
    bullets: sorted.length ? sorted.map(e => `${format(e.date, "d MMM yyyy, h:mm a")} — ${e.label}`) : undefined,
    empty: "No recorded actions found.",
  }];
}

export function buildLegislationSections(caseItem) {
  const list = getRelevantLegislation(caseItem);
  return [{
    heading: "Legislation & Authorities Relevant to This Case",
    bullets: list.map(l => `${l.law} — ${l.why}`),
  }];
}

export function buildStatisticsSections(caseItem, evidence, events, deadlines, merchantResponses, emailLogs) {
  const now = new Date();
  const caseAgeDays = caseItem.created_date ? differenceInDays(now, new Date(caseItem.created_date)) : null;
  const lettersGenerated = Object.values(LETTER_FIELD_MAP).filter(f => caseItem[f]).length;
  const lettersSent = Object.values(LETTER_SENT_FIELD_MAP).filter(f => caseItem[f]).length;
  const completedDeadlines = (deadlines || []).filter(d => d.status === "completed").length;
  const outstandingDeadlines = (deadlines || []).filter(d => d.status === "pending").length;

  const responseTimes = [];
  [
    [caseItem.first_complaint_sent_at, caseItem.first_response_received_at],
    [caseItem.second_complaint_sent_at, caseItem.second_response_received_at],
    [caseItem.third_complaint_sent_at, caseItem.third_response_received_at],
  ].forEach(([sent, received]) => { if (sent && received) responseTimes.push(differenceInDays(new Date(received), new Date(sent))); });
  const avgResponseDays = responseTimes.length ? Math.round(responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length) : null;
  const timeToEscalation = caseItem.first_complaint_sent_at && caseItem.escalated_at
    ? differenceInDays(new Date(caseItem.escalated_at), new Date(caseItem.first_complaint_sent_at))
    : null;

  return [{
    heading: "Case Statistics",
    rows: [
      { label: "Case Age", value: caseAgeDays !== null ? `${caseAgeDays} days` : null },
      { label: "Evidence Files Uploaded", value: String((evidence || []).length) },
      { label: "Letters Generated", value: `${lettersGenerated} of 6` },
      { label: "Letters Sent", value: `${lettersSent} of 6` },
      { label: "Responses Received", value: String((merchantResponses || []).length) },
      { label: "Timeline Events", value: String((events || []).length) },
      { label: "Emails Sent", value: String((emailLogs || []).length) },
      { label: "Deadlines Completed", value: String(completedDeadlines) },
      { label: "Deadlines Outstanding", value: String(outstandingDeadlines) },
      { label: "Average Response Time", value: avgResponseDays !== null ? `${avgResponseDays} days` : "Not yet available" },
      { label: "Time to Escalation", value: timeToEscalation !== null ? `${timeToEscalation} days` : "Not yet escalated" },
    ],
  }];
}