import { Landmark, Shield, Home, Phone, Zap, Scale, Building2, Car, Heart } from "lucide-react";

export const escalationBodies = [
  {
    category: "Banking & Finance (National)",
    icon: "Landmark",
    color: "bg-primary/10 text-primary",
    entries: [
      { name: "Australian Financial Complaints Authority (AFCA)", desc: "Free dispute resolution for banking, insurance, super, credit and investments. Must complain to provider first.", phone: "1800 931 678", url: "https://www.afca.org.au", email: "info@afca.org.au", tags: ["Banking", "Insurance", "Super", "Credit", "National"] },
      { name: "Australian Prudential Regulation Authority (APRA)", desc: "Regulates banks, insurance companies and superannuation funds.", phone: "1300 558 849", url: "https://www.apra.gov.au", email: "info@apra.gov.au", tags: ["Banking", "Insurance", "National"] },
      { name: "Australian Securities & Investments Commission (ASIC)", desc: "Regulates financial services and markets. Lodge complaints via MoneySmart.", phone: "1300 300 630", url: "https://www.asic.gov.au", email: "infoline@asic.gov.au", tags: ["Finance", "Investments", "National"] },
      { name: "MoneySmart (ASIC)", desc: "Free financial guidance and complaint referral tool.", phone: "1300 300 630", url: "https://moneysmart.gov.au", tags: ["Finance", "National"] },
    ],
  },
  {
    category: "Telecommunications (National)",
    icon: "Phone",
    color: "bg-warning/10 text-warning",
    entries: [
      { name: "Telecommunications Industry Ombudsman (TIO)", desc: "Free, independent complaints service for phone and internet disputes.", phone: "1800 062 058", url: "https://www.tio.com.au", email: "tio@tio.com.au", tags: ["Telco", "Internet", "National"] },
      { name: "Australian Communications and Media Authority (ACMA)", desc: "Regulates communications and media industries.", phone: "1300 850 115", url: "https://www.acma.gov.au", email: "info@acma.gov.au", tags: ["Telco", "Media", "National"] },
    ],
  },
  {
    category: "Energy & Utilities (National)",
    icon: "Zap",
    color: "bg-chart-4/10 text-chart-4",
    entries: [
      { name: "Australian Energy Regulator (AER)", desc: "Protects consumers of electricity and gas nationally.", phone: "1300 585 165", url: "https://www.aer.gov.au", email: "AERInquiry@aer.gov.au", tags: ["Energy", "National"] },
      { name: "Energy and Water Ombudsman NSW (EWON)", desc: "Free independent dispute resolution for energy and water in NSW.", phone: "1800 246 545", url: "https://www.ewon.com.au", email: "ewon@ewon.com.au", tags: ["Energy", "Water", "NSW"] },
      { name: "Energy and Water Ombudsman Victoria (EWOV)", desc: "Electricity, gas and water complaints in Victoria.", phone: "1800 500 509", url: "https://www.ewov.com.au", email: "ewov@ewov.com.au", tags: ["Energy", "Water", "VIC"] },
      { name: "Energy & Water Ombudsman Queensland (EWOQ)", desc: "Resolves electricity, gas and water disputes in Queensland.", phone: "1800 662 837", url: "https://www.ewoq.com.au", email: "complaints@ewoq.com.au", tags: ["Energy", "Water", "QLD"] },
      { name: "Energy and Water Ombudsman SA (EWOSA)", desc: "Independent dispute resolution for energy and water in South Australia.", phone: "1800 665 565", url: "https://www.ewosa.com.au", email: "ewosa@ewosa.com.au", tags: ["Energy", "Water", "SA"] },
      { name: "Energy and Water Ombudsman WA (EWOWA)", desc: "Electricity, gas and water complaints in Western Australia.", phone: "1800 754 004", url: "https://www.ombudsman.wa.gov.au/energyandwater", email: "ewon@ombudsman.wa.gov.au", tags: ["Energy", "Water", "WA"] },
      { name: "Ombudsman Tasmania – Energy", desc: "Energy and water dispute resolution in Tasmania.", phone: "1800 001 170", url: "https://www.ombudsman.tas.gov.au", email: "registrar@ombudsman.tas.gov.au", tags: ["Energy", "TAS"] },
      { name: "NT Ombudsman – Utilities", desc: "Utility complaints for NT residents.", phone: "1800 806 380", url: "https://ombudsman.nt.gov.au", email: "ombudsman@nt.gov.au", tags: ["Energy", "NT"] },
    ],
  },
  {
    category: "Tenancy & Housing – NSW",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "NSW Civil and Administrative Tribunal (NCAT)", desc: "Resolves tenancy disputes in NSW including rent, repairs and bond.", phone: "1300 006 228", url: "https://www.ncat.nsw.gov.au", email: "ncat@ncat.nsw.gov.au", tags: ["Tenancy", "NSW"] },
      { name: "NSW Fair Trading – Tenancy", desc: "Rental bonds, repairs and landlord obligations.", phone: "13 32 20", url: "https://www.fairtrading.nsw.gov.au/housing-and-property/renting", email: "ftinfo@fair.nsw.gov.au", tags: ["Tenancy", "NSW"] },
      { name: "Tenants' Union of NSW", desc: "Free advice and advocacy for renters in NSW.", phone: "02 8117 3700", url: "https://www.tenants.org.au", email: "advice@tenants.org.au", tags: ["Tenancy", "NSW"] },
      { name: "NSW Rental Bond Board", desc: "Manage rental bond lodgements and claims.", phone: "13 32 20", url: "https://www.fairtrading.nsw.gov.au/housing-and-property/renting/rental-bonds", tags: ["Bond", "NSW"] },
    ],
  },
  {
    category: "Tenancy & Housing – VIC",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Victorian Civil and Administrative Tribunal (VCAT)", desc: "Residential tenancy disputes in Victoria.", phone: "1300 018 228", url: "https://www.vcat.vic.gov.au", email: "enquiries@vcat.vic.gov.au", tags: ["Tenancy", "VIC"] },
      { name: "Consumer Affairs Victoria – Renting", desc: "Advice on tenant rights, bond claims and landlord obligations.", phone: "1300 558 181", url: "https://www.consumer.vic.gov.au/housing", email: "consumer@justice.vic.gov.au", tags: ["Tenancy", "VIC"] },
      { name: "Tenants Victoria", desc: "Legal advice and tenant advocacy in Victoria.", phone: "03 9416 2577", url: "https://www.tenantsvic.org.au", email: "advice@tenantsvic.org.au", tags: ["Tenancy", "VIC"] },
    ],
  },
  {
    category: "Tenancy & Housing – QLD",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Queensland Civil and Administrative Tribunal (QCAT)", desc: "Resolves residential tenancy disputes in Queensland.", phone: "1300 753 228", url: "https://www.qcat.qld.gov.au", email: "enquiries@qcat.qld.gov.au", tags: ["Tenancy", "QLD"] },
      { name: "Residential Tenancies Authority (RTA)", desc: "Bond, dispute resolution and tenancy advice in QLD.", phone: "1300 366 311", url: "https://www.rta.qld.gov.au", email: "info@rta.qld.gov.au", tags: ["Tenancy", "Bond", "QLD"] },
      { name: "Tenants Queensland", desc: "Free tenancy advice and advocacy in Queensland.", phone: "1300 744 263", url: "https://tenantsqld.org.au", email: "mail@tenantsqld.org.au", tags: ["Tenancy", "QLD"] },
    ],
  },
  {
    category: "Tenancy & Housing – SA",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "South Australian Civil and Administrative Tribunal (SACAT)", desc: "Handles residential tenancy disputes in SA.", phone: "1800 723 767", url: "https://www.sacat.sa.gov.au", email: "sacat@sacat.sa.gov.au", tags: ["Tenancy", "SA"] },
      { name: "Consumer and Business Services SA (CBS)", desc: "Residential tenancy bonds and disputes.", phone: "131 882", url: "https://www.cbs.sa.gov.au/renting", email: "cbs.mail@sa.gov.au", tags: ["Tenancy", "Bond", "SA"] },
      { name: "Shelter SA / Tenants' Advisory Service", desc: "Free tenancy advice in South Australia.", phone: "08 8223 5155", url: "https://www.sheltersa.asn.au", email: "info@sheltersa.asn.au", tags: ["Tenancy", "SA"] },
    ],
  },
  {
    category: "Tenancy & Housing – WA",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Magistrates Court of WA – Residential Tenancy", desc: "Handles residential tenancy disputes in Western Australia.", phone: "08 9425 2222", url: "https://www.magistratescourt.wa.gov.au", tags: ["Tenancy", "WA"] },
      { name: "Consumer Protection WA – Renting", desc: "Advice on tenant rights and bond claims in WA.", phone: "1300 304 054", url: "https://www.consumerprotection.wa.gov.au/home-property/renting", email: "consumer@dmirs.wa.gov.au", tags: ["Tenancy", "Bond", "WA"] },
      { name: "Tenancy WA", desc: "Free tenancy advice and advocacy in WA.", phone: "08 9221 0088", url: "https://www.tenancywa.org.au", email: "admin@tenancywa.org.au", tags: ["Tenancy", "WA"] },
    ],
  },
  {
    category: "Tenancy & Housing – TAS",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Tasmanian Civil and Administrative Tribunal (TASCAT)", desc: "Residential tenancy disputes in Tasmania.", phone: "1300 001 164", url: "https://tascat.tas.gov.au", email: "tascat@tascat.tas.gov.au", tags: ["Tenancy", "TAS"] },
      { name: "Consumer, Building and Occupational Services TAS (CBOS)", desc: "Tenancy bonds, rights and dispute resolution in Tasmania.", phone: "1300 654 499", url: "https://www.cbos.tas.gov.au/topics/housing/rental-and-tenancy", email: "cbos@cbos.tas.gov.au", tags: ["Tenancy", "TAS"] },
      { name: "Tenants' Union of Tasmania", desc: "Free tenancy advice for Tasmanian renters.", phone: "1300 652 641", url: "https://www.tutas.org.au", email: "info@tutas.org.au", tags: ["Tenancy", "TAS"] },
    ],
  },
  {
    category: "Tenancy & Housing – NT",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Northern Territory Civil and Administrative Tribunal (NTCAT)", desc: "Residential tenancy disputes in the NT.", phone: "1800 006 228", url: "https://ntcat.nt.gov.au", email: "ntcat@nt.gov.au", tags: ["Tenancy", "NT"] },
      { name: "NT Consumer Affairs", desc: "Tenancy rights, bonds and landlord obligations in NT.", phone: "1800 019 319", url: "https://consumeraffairs.nt.gov.au", email: "consumer.affairs@nt.gov.au", tags: ["Tenancy", "NT"] },
      { name: "Darwin Community Legal Service", desc: "Free legal help for tenancy issues in NT.", phone: "08 8982 1111", url: "https://www.dcls.org.au", email: "dcls@dcls.org.au", tags: ["Tenancy", "Legal", "NT"] },
    ],
  },
  {
    category: "Tenancy & Housing – ACT",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "ACT Civil and Administrative Tribunal (ACAT)", desc: "Resolves residential tenancy disputes in the ACT.", phone: "02 6207 1740", url: "https://www.acat.act.gov.au", email: "acat@act.gov.au", tags: ["Tenancy", "ACT"] },
      { name: "ACT Rental Bonds", desc: "Rental bond lodgement and release in the ACT.", phone: "13 22 81", url: "https://www.accesscanberra.act.gov.au", tags: ["Tenancy", "Bond", "ACT"] },
      { name: "Tenants' Union ACT", desc: "Free tenancy advice and advocacy in the ACT.", phone: "02 6247 2011", url: "https://www.tenantsact.org.au", email: "admin@tenantsact.org.au", tags: ["Tenancy", "ACT"] },
    ],
  },
  {
    category: "Consumer & Fair Trading – All States",
    icon: "Scale",
    color: "bg-destructive/10 text-destructive",
    entries: [
      { name: "ACCC – Australian Competition and Consumer Commission", desc: "National consumer watchdog. Misleading conduct, unconscionable behaviour, product safety.", phone: "1300 302 502", url: "https://www.accc.gov.au", email: "infocentre@accc.gov.au", tags: ["Consumer", "National"] },
      { name: "NSW Fair Trading", desc: "Consumer protection, product safety, and business conduct in NSW.", phone: "13 32 20", url: "https://www.fairtrading.nsw.gov.au", email: "ftinfo@fair.nsw.gov.au", tags: ["Consumer", "NSW"] },
      { name: "Consumer Affairs Victoria", desc: "Consumer rights, complaints and scam prevention in VIC.", phone: "1300 558 181", url: "https://www.consumer.vic.gov.au", email: "consumer@justice.vic.gov.au", tags: ["Consumer", "VIC"] },
      { name: "Queensland Office of Fair Trading", desc: "Consumer protection and business practices in QLD.", phone: "13 74 68", url: "https://www.qld.gov.au/law/fair-trading", email: "fairtrading@qld.gov.au", tags: ["Consumer", "QLD"] },
      { name: "Consumer and Business Services SA (CBS)", desc: "Consumer rights and business licensing in SA.", phone: "131 882", url: "https://www.cbs.sa.gov.au", email: "cbs.mail@sa.gov.au", tags: ["Consumer", "SA"] },
      { name: "Consumer Protection WA", desc: "Consumer rights and fair trading in Western Australia.", phone: "1300 304 054", url: "https://www.consumerprotection.wa.gov.au", email: "consumer@dmirs.wa.gov.au", tags: ["Consumer", "WA"] },
      { name: "Access Canberra – Fair Trading ACT", desc: "Consumer rights and business conduct in the ACT.", phone: "13 22 81", url: "https://www.accesscanberra.act.gov.au", tags: ["Consumer", "ACT"] },
      { name: "NT Consumer Affairs", desc: "Consumer protection and fair trading in the NT.", phone: "1800 019 319", url: "https://consumeraffairs.nt.gov.au", email: "consumer.affairs@nt.gov.au", tags: ["Consumer", "NT"] },
      { name: "Consumer, Building and Occupational Services TAS", desc: "Consumer rights and fair trading in Tasmania.", phone: "1300 654 499", url: "https://www.cbos.tas.gov.au", email: "cbos@cbos.tas.gov.au", tags: ["Consumer", "TAS"] },
    ],
  },
  {
    category: "Ombudsman – State & Territory",
    icon: "Building2",
    color: "bg-accent/10 text-accent",
    entries: [
      { name: "NSW Ombudsman", desc: "Investigates complaints about NSW government agencies and certain private sector.", phone: "02 9286 1000", url: "https://www.ombo.nsw.gov.au", email: "nswombo@ombo.nsw.gov.au", tags: ["Government", "NSW"] },
      { name: "Victorian Ombudsman", desc: "Investigates complaints about Victorian government.", phone: "1800 806 314", url: "https://www.ombudsman.vic.gov.au", email: "ombudsman@ombudsman.vic.gov.au", tags: ["Government", "VIC"] },
      { name: "Queensland Ombudsman", desc: "Investigates complaints about Queensland government and public agencies.", phone: "07 3005 7000", url: "https://www.ombudsman.qld.gov.au", email: "ombudsman@ombudsman.qld.gov.au", tags: ["Government", "QLD"] },
      { name: "SA Ombudsman", desc: "Investigates complaints about SA government agencies.", phone: "08 8226 8699", url: "https://www.ombudsman.sa.gov.au", email: "ombudsman@ombudsman.sa.gov.au", tags: ["Government", "SA"] },
      { name: "WA Ombudsman", desc: "Investigates complaints about WA government agencies.", phone: "08 9220 7555", url: "https://www.ombudsman.wa.gov.au", email: "ombudsman@ombudsman.wa.gov.au", tags: ["Government", "WA"] },
      { name: "ACT Ombudsman", desc: "Handles complaints about ACT government agencies.", phone: "1300 362 072", url: "https://www.ombudsman.gov.au", tags: ["Government", "ACT"] },
      { name: "NT Ombudsman", desc: "Investigates complaints about NT government agencies.", phone: "1800 806 380", url: "https://ombudsman.nt.gov.au", email: "ombudsman@nt.gov.au", tags: ["Government", "NT"] },
      { name: "TAS Ombudsman", desc: "Investigates complaints about Tasmanian government and public authorities.", phone: "1800 001 170", url: "https://www.ombudsman.tas.gov.au", email: "registrar@ombudsman.tas.gov.au", tags: ["Government", "TAS"] },
      { name: "Commonwealth Ombudsman", desc: "Handles complaints about Australian Government agencies.", phone: "1300 362 072", url: "https://www.ombudsman.gov.au", email: "ombudsman@ombudsman.gov.au", tags: ["Government", "National"] },
    ],
  },
  {
    category: "Legal Aid & Community Legal Centres",
    icon: "Scale",
    color: "bg-primary/10 text-primary",
    entries: [
      { name: "Legal Aid NSW", desc: "Free legal advice for eligible people in NSW.", phone: "1300 888 529", url: "https://www.legalaid.nsw.gov.au", tags: ["Legal", "NSW"] },
      { name: "Victoria Legal Aid", desc: "Free legal help for Victorians.", phone: "1300 792 387", url: "https://www.legalaid.vic.gov.au", tags: ["Legal", "VIC"] },
      { name: "Legal Aid Queensland", desc: "Free legal advice and representation in QLD.", phone: "1300 651 188", url: "https://www.legalaid.qld.gov.au", tags: ["Legal", "QLD"] },
      { name: "Legal Services Commission SA", desc: "Free and subsidised legal services in SA.", phone: "1300 366 424", url: "https://www.lsc.sa.gov.au", tags: ["Legal", "SA"] },
      { name: "Legal Aid WA", desc: "Free legal services in Western Australia.", phone: "1300 650 579", url: "https://www.legalaid.wa.gov.au", tags: ["Legal", "WA"] },
      { name: "Legal Aid ACT", desc: "Free legal advice in the ACT.", phone: "02 6243 8197", url: "https://www.legalaidact.org.au", tags: ["Legal", "ACT"] },
      { name: "Northern Territory Legal Aid Commission", desc: "Free legal services for NT residents.", phone: "1800 019 343", url: "https://www.ntlac.nt.gov.au", tags: ["Legal", "NT"] },
      { name: "Legal Aid Commission of Tasmania", desc: "Free legal advice in Tasmania.", phone: "1300 366 611", url: "https://www.legalaid.tas.gov.au", tags: ["Legal", "TAS"] },
      { name: "Community Legal Centres Australia", desc: "Find a community legal centre near you.", phone: "02 9264 9595", url: "https://clcs.org.au", tags: ["Legal", "National"] },
    ],
  },
];

export const contactDirectory = [
  {
    category: "Major Banks",
    icon: "Landmark",
    color: "bg-primary/10 text-primary",
    entries: [
      { name: "Commonwealth Bank (CBA)", desc: "Complaints: Call 13 2221 or visit a branch. Escalate to AFCA if unresolved within 30 days.", phone: "13 2221", url: "https://www.commbank.com.au/support/feedback.html", email: "Not available – use online form", tags: ["Bank", "CBA"] },
      { name: "Westpac Banking Corporation", desc: "Customer feedback and complaints. Escalate to AFCA after 45 days.", phone: "132 032", url: "https://www.westpac.com.au/about-westpac/contact-us/complaints", email: "customer.complaints@westpac.com.au", tags: ["Bank", "Westpac"] },
      { name: "ANZ Bank", desc: "Formal complaints line. Must complain to ANZ before escalating to AFCA.", phone: "13 13 14", url: "https://www.anz.com.au/support/complaints", email: "anz.feedback@anz.com", tags: ["Bank", "ANZ"] },
      { name: "NAB – National Australia Bank", desc: "Complaints and dispute resolution.", phone: "13 22 65", url: "https://www.nab.com.au/about-us/contact-us/feedback-and-complaints", email: "nabcomplaintsoffice@nab.com.au", tags: ["Bank", "NAB"] },
      { name: "Bendigo Bank", desc: "Customer complaints and feedback.", phone: "1300 236 344", url: "https://www.bendigobank.com.au/contact/complaints", email: "complaints@bendigoadelaide.com.au", tags: ["Bank", "Bendigo"] },
      { name: "Bank of Queensland (BOQ)", desc: "Complaints resolution team.", phone: "1300 55 72 72", url: "https://www.boq.com.au/contact-us/complaints", email: "customerrelations@boq.com.au", tags: ["Bank", "BOQ"] },
      { name: "ING Australia", desc: "Customer complaints and disputes.", phone: "133 464", url: "https://www.ing.com.au/help/contact/feedback.html", email: "feedback@ing.com.au", tags: ["Bank", "ING"] },
      { name: "Suncorp Bank", desc: "Customer complaints team.", phone: "13 11 55", url: "https://www.suncorp.com.au/banking/help/complaints.html", email: "customerrelations@suncorp.com.au", tags: ["Bank", "Suncorp"] },
      { name: "St George Bank", desc: "Complaints (part of Westpac Group).", phone: "13 33 30", url: "https://www.stgeorge.com.au/about/feedback-complaints", tags: ["Bank", "St George"] },
      { name: "Macquarie Bank", desc: "Customer complaints and escalations.", phone: "1800 806 310", url: "https://www.macquarie.com/au/personal/contact-us/complaints", email: "complaints@macquarie.com", tags: ["Bank", "Macquarie"] },
      { name: "HSBC Australia", desc: "Customer complaints and dispute resolution.", phone: "1300 308 008", url: "https://www.hsbc.com.au/help/complaints", tags: ["Bank", "HSBC"] },
      { name: "Citibank Australia", desc: "Customer complaints — now part of NAB.", phone: "13 24 84", url: "https://www.citibank.com.au/aus/homepage/feedback.htm", tags: ["Bank", "Citi"] },
      { name: "MyState Bank (TAS)", desc: "Tasmania-based bank complaints.", phone: "138 001", url: "https://www.mystate.com.au/feedback", email: "customerservice@mystate.com.au", tags: ["Bank", "TAS"] },
      { name: "Heritage Bank (QLD)", desc: "QLD-based bank complaints.", phone: "13 14 22", url: "https://www.heritagebankau.com/contact-us", email: "customerservice@heritagebankau.com", tags: ["Bank", "QLD"] },
      { name: "Police Credit Union (SA)", desc: "SA-based credit union complaints.", phone: "13 27 27", url: "https://www.policecu.com.au/contact", tags: ["Bank", "SA"] },
    ],
  },
  {
    category: "Telecommunications Providers",
    icon: "Phone",
    color: "bg-warning/10 text-warning",
    entries: [
      { name: "Telstra", desc: "Formal complaints and escalations. Escalate to TIO after 10 days.", phone: "13 22 00", url: "https://www.telstra.com.au/contact-us/complaints", tags: ["Telco", "Telstra"] },
      { name: "Optus", desc: "Customer complaints team. Escalate to TIO after 10 days.", phone: "1300 300 937", url: "https://www.optus.com.au/support/contact-us/complaints", email: "customer.advocate@optus.com.au", tags: ["Telco", "Optus"] },
      { name: "Vodafone Australia", desc: "Formal complaints. Escalate to TIO after 10 days.", phone: "1300 650 410", url: "https://www.vodafone.com.au/support/complaints", email: "complaints@vodafone.com.au", tags: ["Telco", "Vodafone"] },
      { name: "TPG Telecom", desc: "Customer complaints and feedback.", phone: "13 14 23", url: "https://www.tpg.com.au/contact/complaints", tags: ["Telco", "TPG"] },
      { name: "iiNet", desc: "Customer complaints (part of TPG Group).", phone: "13 19 17", url: "https://www.iinet.net.au/contact/feedback", email: "complaints@iinet.net.au", tags: ["Telco", "iiNet"] },
      { name: "Aussie Broadband", desc: "Customer feedback and dispute resolution.", phone: "1300 880 905", url: "https://www.aussiebroadband.com.au/help-centre/complaints", email: "complaints@aussiebroadband.com.au", tags: ["Telco", "Aussie BB"] },
      { name: "Belong (Telstra)", desc: "Complaints handled via Telstra's process.", phone: "13 22 00", url: "https://www.belong.com.au/contact", tags: ["Telco", "Belong"] },
      { name: "Spintel", desc: "Customer complaints and TIO escalation support.", phone: "1300 303 375", url: "https://www.spintel.net.au/contact-us", email: "support@spintel.net.au", tags: ["Telco"] },
      { name: "Superloop", desc: "Internet and telco complaints.", phone: "1300 787 353", url: "https://www.superloop.com/support/contact.html", tags: ["Telco"] },
    ],
  },
  {
    category: "Energy Providers",
    icon: "Zap",
    color: "bg-chart-4/10 text-chart-4",
    entries: [
      { name: "AGL Energy", desc: "Customer complaints for electricity and gas. Escalate to energy ombudsman if unresolved.", phone: "131 245", url: "https://www.agl.com.au/about-agl/contact-us/complaints", email: "customercomplaints@agl.com.au", tags: ["Energy", "AGL"] },
      { name: "Origin Energy", desc: "Customer complaints for electricity and gas.", phone: "13 24 61", url: "https://www.originenergy.com.au/about/contact-us/feedback-and-complaints", email: "complaints@originenergy.com.au", tags: ["Energy", "Origin"] },
      { name: "EnergyAustralia", desc: "Customer complaints team.", phone: "133 466", url: "https://www.energyaustralia.com.au/home/complaints-and-feedback", tags: ["Energy", "EnergyAustralia"] },
      { name: "Alinta Energy", desc: "Customer complaints and disputes.", phone: "13 37 02", url: "https://www.alintaenergy.com.au/help/feedback-and-complaints", tags: ["Energy", "Alinta"] },
      { name: "Ergon Energy (QLD)", desc: "Customer disputes for QLD customers.", phone: "13 10 46", url: "https://www.ergon.com.au/contact-us/feedback-and-complaints", email: "customercomplaints@ergon.com.au", tags: ["Energy", "QLD"] },
      { name: "Endeavour Energy (NSW)", desc: "Electricity network complaints in NSW.", phone: "13 17 18", url: "https://www.endeavourenergy.com.au/contact/complaints", tags: ["Energy", "NSW"] },
      { name: "Synergy (WA)", desc: "Electricity and gas in WA.", phone: "13 13 53", url: "https://www.synergy.net.au/contact-us/feedback-complaints", email: "feedback@synergy.net.au", tags: ["Energy", "WA"] },
      { name: "SA Power Networks", desc: "Electricity network complaints in SA.", phone: "13 12 61", url: "https://www.sapowernetworks.com.au/contact-us/complaints", email: "customercomplaints@sapowernetworks.com.au", tags: ["Energy", "SA"] },
      { name: "TasNetworks (TAS)", desc: "Electricity network complaints in Tasmania.", phone: "1300 137 008", url: "https://www.tasnetworks.com.au/contact-us/feedback-and-complaints", email: "feedback@tasnetworks.com.au", tags: ["Energy", "TAS"] },
      { name: "Power and Water Corporation (NT)", desc: "Electricity, water and sewage complaints in NT.", phone: "1800 245 092", url: "https://www.powerwater.com.au/contact-us/feedback", email: "customerservice@powerwater.com.au", tags: ["Energy", "Water", "NT"] },
      { name: "ActewAGL (ACT)", desc: "Electricity and gas complaints in ACT.", phone: "13 14 93", url: "https://www.actewagl.com.au/contact-us/feedback-and-complaints", email: "customerservice@actewagl.com.au", tags: ["Energy", "ACT"] },
    ],
  },
  {
    category: "Insurance Companies",
    icon: "Shield",
    color: "bg-accent/10 text-accent",
    entries: [
      { name: "NRMA Insurance", desc: "Customer complaints and claims disputes. Escalate to AFCA.", phone: "132 132", url: "https://www.nrma.com.au/contact-us/complaints", tags: ["Insurance", "NRMA"] },
      { name: "RACQ Insurance (QLD)", desc: "QLD-based insurance complaints.", phone: "13 19 05", url: "https://www.racq.com.au/insurance/complaints", tags: ["Insurance", "RACQ", "QLD"] },
      { name: "RACV Insurance (VIC)", desc: "VIC-based insurance complaints.", phone: "13 72 28", url: "https://www.racv.com.au/insurance/feedback-complaints.html", tags: ["Insurance", "RACV", "VIC"] },
      { name: "RAA Insurance (SA)", desc: "SA-based insurance complaints.", phone: "08 8202 4600", url: "https://www.raa.com.au/insurance/complaints", tags: ["Insurance", "RAA", "SA"] },
      { name: "RAC Insurance (WA)", desc: "WA-based insurance complaints.", phone: "13 17 03", url: "https://www.rac.com.au/insurance/feedback-complaints", tags: ["Insurance", "RAC", "WA"] },
      { name: "RACT Insurance (TAS)", desc: "TAS-based insurance complaints.", phone: "13 27 22", url: "https://www.ract.com.au/insurance/feedback", tags: ["Insurance", "RACT", "TAS"] },
      { name: "Allianz Australia", desc: "Customer complaints for all Allianz products.", phone: "1300 555 030", url: "https://www.allianz.com.au/contact-us/complaints", email: "complaints@allianz.com.au", tags: ["Insurance", "Allianz"] },
      { name: "CGU Insurance", desc: "Customer complaints team.", phone: "13 24 80", url: "https://www.cgu.com.au/contact-us/feedback-complaints", email: "customer.relations@iag.com.au", tags: ["Insurance", "CGU"] },
      { name: "Suncorp Insurance", desc: "General insurance complaints.", phone: "13 11 55", url: "https://www.suncorp.com.au/insurance/help/complaints.html", email: "customerrelations@suncorp.com.au", tags: ["Insurance", "Suncorp"] },
      { name: "Medibank Private", desc: "Health insurance complaints and disputes.", phone: "132 331", url: "https://www.medibank.com.au/contact-us/feedback-complaints", tags: ["Insurance", "Health", "Medibank"] },
      { name: "Bupa Australia", desc: "Health insurance complaints.", phone: "134 135", url: "https://www.bupa.com.au/contact/feedback-complaints", tags: ["Insurance", "Health", "Bupa"] },
      { name: "HCF Health Insurance", desc: "Health insurance disputes.", phone: "13 13 34", url: "https://www.hcf.com.au/contact-us/feedback", tags: ["Insurance", "Health", "HCF"] },
      { name: "NIB Health Funds", desc: "Health insurance complaints.", phone: "13 14 63", url: "https://www.nib.com.au/contact-us/complaints", email: "feedback@nib.com.au", tags: ["Insurance", "Health", "NIB"] },
      { name: "QBE Insurance", desc: "Customer complaints and claims disputes.", phone: "133 723", url: "https://www.qbe.com/au/contact-us/complaints", email: "customerrelations@qbe.com", tags: ["Insurance", "QBE"] },
      { name: "Budget Direct", desc: "Insurance complaints and disputes.", phone: "1300 139 422", url: "https://www.budgetdirect.com.au/contact-us/feedback.html", tags: ["Insurance", "Budget Direct"] },
    ],
  },
  {
    category: "Real Estate Agencies",
    icon: "Home",
    color: "bg-success/10 text-success",
    entries: [
      { name: "Ray White Complaints", desc: "Complaints about Ray White agents or property management. Contact head office or state regulator.", phone: "07 3231 2300", url: "https://www.raywhite.com/contact", email: "info@raywhite.com", tags: ["Real Estate", "Ray White"] },
      { name: "LJ Hooker Complaints", desc: "Complaints about LJ Hooker agents. Contact head office or state property regulator.", phone: "02 9220 4700", url: "https://www.ljhooker.com.au/contact-us", email: "info@ljhooker.com.au", tags: ["Real Estate", "LJ Hooker"] },
      { name: "McGrath Estate Agents", desc: "Feedback and complaints to McGrath head office.", phone: "02 9960 1000", url: "https://www.mcgrath.com.au/contact", email: "info@mcgrath.com.au", tags: ["Real Estate", "McGrath"] },
      { name: "Harcourts Australia", desc: "Complaints about Harcourts agents and property management.", phone: "03 9604 9800", url: "https://www.harcourts.com.au/Contact-Us", email: "info@harcourts.net", tags: ["Real Estate", "Harcourts"] },
      { name: "NSW Fair Trading – Property Agents", desc: "Complaints about agents and property management in NSW.", phone: "13 32 20", url: "https://www.fairtrading.nsw.gov.au/property-and-land/property-agents", email: "ftinfo@fair.nsw.gov.au", tags: ["Real Estate", "NSW"] },
      { name: "Consumer Affairs VIC – Estate Agents", desc: "Complaints about estate agents and property managers in VIC.", phone: "1300 558 181", url: "https://www.consumer.vic.gov.au/housing/estate-agents", email: "consumer@justice.vic.gov.au", tags: ["Real Estate", "VIC"] },
      { name: "Office of Fair Trading QLD – Property", desc: "Agent complaints and licensing in QLD.", phone: "13 74 68", url: "https://www.qld.gov.au/law/fair-trading/buying-products-and-services/real-estate", tags: ["Real Estate", "QLD"] },
      { name: "Consumer Protection WA – Property", desc: "Real estate agent complaints in WA.", phone: "1300 304 054", url: "https://www.consumerprotection.wa.gov.au/home-property/real-estate", tags: ["Real Estate", "WA"] },
      { name: "CBS SA – Property", desc: "Property agent complaints in SA.", phone: "131 882", url: "https://www.cbs.sa.gov.au/propertymanagement", tags: ["Real Estate", "SA"] },
      { name: "CBOS TAS – Property", desc: "Property agent complaints in Tasmania.", phone: "1300 654 499", url: "https://www.cbos.tas.gov.au/topics/housing/real-estate-agents", tags: ["Real Estate", "TAS"] },
    ],
  },
  {
    category: "Housing & Social Services",
    icon: "Building2",
    color: "bg-chart-2/10 text-chart-2",
    entries: [
      { name: "NSW Housing (DCJ Housing)", desc: "Social housing complaints and maintenance in NSW.", phone: "1800 422 322", url: "https://www.facs.nsw.gov.au/housing", tags: ["Social Housing", "NSW"] },
      { name: "Housing Victoria", desc: "Public housing complaints in Victoria.", phone: "1800 656 600", url: "https://www.housing.vic.gov.au", tags: ["Social Housing", "VIC"] },
      { name: "Housing Queensland", desc: "Social housing complaints in Queensland.", phone: "13 74 68", url: "https://www.housing.qld.gov.au", tags: ["Social Housing", "QLD"] },
      { name: "SA Housing Authority", desc: "Public housing and repairs in SA.", phone: "131 299", url: "https://www.housing.sa.gov.au", email: "sahousing@sa.gov.au", tags: ["Social Housing", "SA"] },
      { name: "Department of Communities WA Housing", desc: "Social housing complaints in WA.", phone: "1800 176 888", url: "https://www.communities.wa.gov.au/housing", tags: ["Social Housing", "WA"] },
      { name: "Housing Tasmania", desc: "Public housing complaints and repairs in Tasmania.", phone: "1300 665 663", url: "https://www.housing.tas.gov.au", email: "housingtasmania@communities.tas.gov.au", tags: ["Social Housing", "TAS"] },
      { name: "NT Housing (Territory Housing)", desc: "Public housing complaints in the Northern Territory.", phone: "1800 234 678", url: "https://housing.nt.gov.au", tags: ["Social Housing", "NT"] },
      { name: "ACT Housing (Community Services Directorate)", desc: "Public housing complaints in the ACT.", phone: "13 34 27", url: "https://www.communityservices.act.gov.au/housing", tags: ["Social Housing", "ACT"] },
      { name: "Homelessness Australia", desc: "National peak body for homelessness services.", phone: "02 6247 4580", url: "https://www.homelessnessaustralia.org.au", email: "info@homelessnessaustralia.org.au", tags: ["Housing", "Homelessness", "National"] },
    ],
  },
  {
    category: "Health Services & Medicare",
    icon: "Heart",
    color: "bg-destructive/10 text-destructive",
    entries: [
      { name: "Australian Health Practitioner Regulation Agency (AHPRA)", desc: "Complaints about registered health practitioners (doctors, nurses, dentists, etc.).", phone: "1300 419 495", url: "https://www.ahpra.gov.au/notifications", email: "notifications@ahpra.gov.au", tags: ["Health", "National"] },
      { name: "Private Health Insurance Ombudsman", desc: "Complaints about private health insurers.", phone: "1800 640 695", url: "https://www.privatehealth.gov.au", email: "phio@ombudsman.gov.au", tags: ["Health", "Insurance", "National"] },
      { name: "Services Australia (Medicare)", desc: "Medicare billing disputes and complaints.", phone: "132 011", url: "https://www.servicesaustralia.gov.au/contact-us", tags: ["Health", "Medicare", "National"] },
      { name: "Health Care Complaints Commission NSW (HCCC)", desc: "Complaints about health practitioners and facilities in NSW.", phone: "1800 043 159", url: "https://www.hccc.nsw.gov.au", email: "hccc@hccc.nsw.gov.au", tags: ["Health", "NSW"] },
      { name: "Health Complaints Commissioner VIC", desc: "Complaints about health services in Victoria.", phone: "1300 582 113", url: "https://www.hcc.vic.gov.au", email: "hcc@hcc.vic.gov.au", tags: ["Health", "VIC"] },
      { name: "Office of the Health Ombudsman QLD", desc: "Health practitioner complaints in Queensland.", phone: "133 646", url: "https://www.oho.qld.gov.au", email: "complaints@oho.qld.gov.au", tags: ["Health", "QLD"] },
      { name: "SA Health and Community Services Complaints Commissioner", desc: "Health complaints in SA.", phone: "08 8226 8666", url: "https://www.hcscc.sa.gov.au", email: "hcscc@sa.gov.au", tags: ["Health", "SA"] },
      { name: "Health and Disability Services Complaints Office WA (HaDSCO)", desc: "Health and disability complaints in WA.", phone: "1800 813 583", url: "https://www.hadsco.wa.gov.au", email: "hadsco@hadsco.wa.gov.au", tags: ["Health", "WA"] },
      { name: "Health Complaints Commissioner TAS", desc: "Health complaints in Tasmania.", phone: "1800 001 170", url: "https://www.ombudsman.tas.gov.au", tags: ["Health", "TAS"] },
      { name: "Health and Community Services Complaints Commissioner NT", desc: "Health complaints in NT.", phone: "1800 004 474", url: "https://hcscc.nt.gov.au", tags: ["Health", "NT"] },
    ],
  },
  {
    category: "Superannuation & Investments",
    icon: "Landmark",
    color: "bg-primary/10 text-primary",
    entries: [
      { name: "Australian Taxation Office (ATO) – Super", desc: "Lost super, superannuation guarantee complaints.", phone: "13 10 20", url: "https://www.ato.gov.au/individuals/super", tags: ["Super", "National"] },
      { name: "Australian Super", desc: "Member complaints for AustralianSuper.", phone: "1300 300 273", url: "https://www.australiansuper.com/contact-us/complaints", email: "feedback@australiansuper.com", tags: ["Super", "National"] },
      { name: "Hostplus", desc: "Superannuation complaints.", phone: "1300 467 875", url: "https://hostplus.com.au/contact-us/feedback-and-complaints", email: "feedback@hostplus.com.au", tags: ["Super", "National"] },
      { name: "REST Super", desc: "Super complaints and disputes.", phone: "1300 300 778", url: "https://rest.com.au/contact/feedback", email: "rest@rest.com.au", tags: ["Super", "National"] },
      { name: "CBUS Super", desc: "Construction industry super complaints.", phone: "1300 361 784", url: "https://www.cbus.com.au/contact-us/complaints", tags: ["Super", "National"] },
    ],
  },
  {
    category: "Government Services",
    icon: "Building2",
    color: "bg-muted/40 text-muted-foreground",
    entries: [
      { name: "Services Australia (Centrelink)", desc: "Centrelink payment disputes and complaints.", phone: "132 850", url: "https://www.servicesaustralia.gov.au/contact-us", tags: ["Government", "Centrelink", "National"] },
      { name: "National Disability Insurance Agency (NDIA)", desc: "NDIS plan disputes and service complaints.", phone: "1800 800 110", url: "https://www.ndis.gov.au/contact/complaints", email: "feedback@ndis.gov.au", tags: ["NDIS", "Disability", "National"] },
      { name: "NDIS Quality and Safeguards Commission", desc: "Complaints about NDIS providers.", phone: "1800 035 544", url: "https://www.ndiscommission.gov.au/participants/complaints", email: "complaints@ndiscommission.gov.au", tags: ["NDIS", "National"] },
      { name: "Australian Border Force", desc: "Complaints about visa, customs and border services.", phone: "131 881", url: "https://www.abf.gov.au/about-us/contact-us/complaints", tags: ["Government", "Visa", "National"] },
      { name: "Australian Taxation Office (ATO)", desc: "Tax disputes and complaints.", phone: "13 28 61", url: "https://www.ato.gov.au/about-ato/accountability-and-governance/complaints", tags: ["Tax", "National"] },
      { name: "Fair Work Commission", desc: "Unfair dismissal, general protections and workplace disputes.", phone: "1300 799 675", url: "https://www.fwc.gov.au", email: "helpline@fwc.gov.au", tags: ["Employment", "National"] },
      { name: "Fair Work Ombudsman", desc: "Underpayment, workplace rights and award breaches.", phone: "13 13 94", url: "https://www.fairwork.gov.au", tags: ["Employment", "National"] },
      { name: "Australian Human Rights Commission", desc: "Discrimination, harassment and human rights complaints.", phone: "1300 656 419", url: "https://humanrights.gov.au/complaints", email: "complaintsinfo@humanrights.gov.au", tags: ["Rights", "Discrimination", "National"] },
    ],
  },
  {
    category: "Transport & Automotive",
    icon: "Car",
    color: "bg-chart-3/10 text-chart-3",
    entries: [
      { name: "Motor Vehicle Industry Authority NSW", desc: "Complaints about car dealers and repairers in NSW.", phone: "13 32 20", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/motor-vehicle-industry", tags: ["Automotive", "NSW"] },
      { name: "Consumer Affairs VIC – Motor Vehicles", desc: "Car dealer and repairer complaints in VIC.", phone: "1300 558 181", url: "https://www.consumer.vic.gov.au/cars", tags: ["Automotive", "VIC"] },
      { name: "Office of Fair Trading QLD – Motor Vehicles", desc: "Vehicle dealer complaints in QLD.", phone: "13 74 68", url: "https://www.qld.gov.au/transport/buying-vehicle", tags: ["Automotive", "QLD"] },
      { name: "Consumer Protection WA – Motor Vehicles", desc: "Car dealer and repairer complaints in WA.", phone: "1300 304 054", url: "https://www.consumerprotection.wa.gov.au/vehicles", tags: ["Automotive", "WA"] },
      { name: "CBS SA – Motor Vehicles", desc: "Vehicle dealer complaints in SA.", phone: "131 882", url: "https://www.cbs.sa.gov.au/motorvehicles", tags: ["Automotive", "SA"] },
      { name: "Lemon Laws – ACCC", desc: "Defective vehicle rights under Australian Consumer Law.", phone: "1300 302 502", url: "https://www.accc.gov.au/consumers/cars-transport", tags: ["Automotive", "National"] },
    ],
  },
];