/**
 * CHAOS CONTROLLER™ — THE ONLY PDF ENGINE IN THIS APP
 *
 * Every export (letter preview/download/print/email, dashboard report,
 * AI analysis, case transfer package) captures a live DOM node built from
 * components/letters/LetterDocument.jsx or components/reports/ReportDocument.jsx
 * via html2canvas, then paginates it into an A4 PDF here.
 *
 * captureDocumentPDF() is the ONLY PDF generation function in the app.
 * Do not add a second renderer or a second jsPDF text-drawing path —
 * extend LetterDocument / ReportDocument instead.
 */

import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { format } from 'date-fns';

const A4_W = 210; // mm
const A4_H = 297; // mm
const FOOTER_ZONE = 6; // mm reserved at the bottom of every page for the branded footer

// Wait for every <img> inside a node to finish loading (or time out) before
// capture — prevents blank/clipped images on the first render of a hidden node.
function waitForImages(el, timeoutMs = 5000) {
  const imgs = Array.from(el.querySelectorAll('img'));
  return Promise.all(imgs.map((img) => {
    if (img.complete && img.naturalWidth > 0) return Promise.resolve();
    return new Promise((resolve) => {
      const done = () => resolve();
      img.addEventListener('load', done, { once: true });
      img.addEventListener('error', done, { once: true });
      setTimeout(done, timeoutMs);
    });
  }));
}

/**
 * captureDocumentPDF — the ONLY PDF generation function in the app.
 * Captures a live DOM node (LetterDocument or ReportDocument) into an A4 PDF
 * and stamps a branded footer (Chaos Controller, Case ID, generated date,
 * page X of Y) on every page.
 */
export async function captureDocumentPDF(domNode, { caseId, generatedDate } = {}) {
  if (!domNode) throw new Error('captureDocumentPDF: domNode is null');

  const el = domNode.querySelector ? (domNode.querySelector('.letter-page') || domNode) : domNode;
  await waitForImages(el);

  const prevShadow = el.style.boxShadow;
  el.style.boxShadow = 'none';

  let canvas;
  try {
    canvas = await html2canvas(el, {
      scale: 2,
      useCORS: true,
      allowTaint: false,
      backgroundColor: '#ffffff',
      logging: false,
      windowWidth: el.scrollWidth,
      width: el.scrollWidth,
      height: el.scrollHeight,
    });
  } finally {
    el.style.boxShadow = prevShadow;
  }

  const imgData = canvas.toDataURL('image/jpeg', 0.95);
  const imgPxW = canvas.width;
  const imgPxH = canvas.height;
  const imgMmH = (imgPxH / imgPxW) * A4_W;
  const usableH = A4_H - FOOTER_ZONE;
  const totalPages = Math.max(1, Math.ceil(imgMmH / usableH));

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const caseRef = caseId ? `CC-${String(caseId).slice(0, 8).toUpperCase()}` : '';
  const dateLabel = generatedDate || format(new Date(), 'd MMMM yyyy');

  for (let page = 0; page < totalPages; page++) {
    if (page > 0) pdf.addPage();
    const yOffset = -(page * usableH);
    pdf.addImage(imgData, 'JPEG', 0, yOffset, A4_W, imgMmH);

    // Branded footer — every page
    pdf.setDrawColor(210);
    pdf.setLineWidth(0.2);
    pdf.line(10, A4_H - FOOTER_ZONE + 1, A4_W - 10, A4_H - FOOTER_ZONE + 1);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7);
    pdf.setTextColor(120);
    const left = `Generated by Chaos Controller${caseRef ? '  •  Case ' + caseRef : ''}  •  ${dateLabel}`;
    pdf.text(left, 10, A4_H - FOOTER_ZONE + 4.5);
    pdf.text(`Page ${page + 1} of ${totalPages}`, A4_W - 10, A4_H - FOOTER_ZONE + 4.5, { align: 'right' });
    pdf.setTextColor(0);
  }

  return pdf.output('blob');
}

// Backward-compatible alias — same function, used by letter call sites.
export const captureLetterDocumentPDF = captureDocumentPDF;

// ─────────────────────────────────────────────────────────────────────────────
// DOWNLOAD — triggers browser file save
// ─────────────────────────────────────────────────────────────────────────────
export function downloadPDFBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}

// ─────────────────────────────────────────────────────────────────────────────
// PRINT — renders PDF in a hidden iframe to suppress browser URL/header/footer.
// Falls back to download if iframe fails.
// ─────────────────────────────────────────────────────────────────────────────
export async function openPDFForPrint(blob, filename = 'document.pdf') {
  try {
    const url = URL.createObjectURL(blob);

    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:none;';
    document.body.appendChild(iframe);

    await new Promise((resolve, reject) => {
      const cleanup = () => {
        setTimeout(() => {
          try { document.body.removeChild(iframe); } catch (e) {}
          URL.revokeObjectURL(url);
        }, 60000);
      };

      iframe.onload = () => {
        try {
          iframe.contentWindow.focus();
          iframe.contentWindow.print();
          cleanup();
          resolve(true);
        } catch (e) {
          cleanup();
          reject(e);
        }
      };

      iframe.onerror = () => { cleanup(); reject(new Error('iframe load failed')); };
      iframe.src = url;

      // Safari fallback — onload may not fire for blob URLs
      setTimeout(() => {
        try {
          iframe.contentWindow.focus();
          iframe.contentWindow.print();
          cleanup();
          resolve(true);
        } catch (e) {
          cleanup();
          reject(e);
        }
      }, 2000);
    });

    return true;
  } catch (error) {
    console.error('[PDF] openPDFForPrint failed, falling back to download:', error);
    downloadPDFBlob(blob, filename);
    return false;
  }
}