// ─── Chaos Controller — Full Provider Dataset ─────────────────────────────────
// Canonical structure for every provider card.

export const providers = [

  // ── FEDERAL / NATIONAL ────────────────────────────────────────────────────

  { id:"afca", name:"AFCA", acronym:"AFCA", fullName:"Australian Financial Complaints Authority", category:"Banking & Finance", serviceType:"Ombudsman", jurisdiction:"National", state:"National", description:"Free, independent dispute resolution for banking, insurance, superannuation, credit and investment complaints.", whatTheyDo:"Investigates and resolves disputes between consumers and financial services providers.", useThisWhen:["Your bank, insurer or super fund hasn't resolved your complaint in 30–45 days","You received an unsatisfactory final response","You were charged incorrect fees or had a claim wrongly denied","The organisation is not engaging"], handles:["Banking disputes","Insurance claims","Super complaints","Credit disputes","Investment issues"], referralType:"Self-refer", phone:"1800 931 678", website:"https://www.afca.org.au", emergency:false, tags:["Banking","Insurance","Super","Credit","Finance","National"] },

  { id:"asic", name:"ASIC", acronym:"ASIC", fullName:"Australian Securities and Investments Commission", category:"Banking & Finance", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Regulates financial services and markets. Handles misconduct reports for advisers, brokers and lenders.", whatTheyDo:"Regulates financial services and markets, takes enforcement action, provides guidance via MoneySmart.", useThisWhen:["A financial adviser gave you bad advice","You suspect financial fraud or misconduct","A company is engaging in misleading financial conduct"], handles:["Financial misconduct","Adviser complaints","Market manipulation","Unlicensed operators"], referralType:"Self-refer", phone:"1300 300 630", website:"https://www.asic.gov.au", emergency:false, tags:["Finance","Investments","Fraud","National"] },

  { id:"apra", name:"APRA", acronym:"APRA", fullName:"Australian Prudential Regulation Authority", category:"Banking & Finance", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Regulates banks, insurers and superannuation funds to ensure they remain financially sound.", whatTheyDo:"Supervises financial institutions for safety and stability. Handles systemic concerns.", useThisWhen:["You believe a bank or insurer is operating unsafely","You want to report systemic issues","AFCA cannot help with your matter"], handles:["Banking regulation","Insurance regulation","Super fund oversight"], referralType:"Self-refer", phone:"1300 558 849", website:"https://www.apra.gov.au", emergency:false, tags:["Banking","Insurance","Super","National"] },

  { id:"accc", name:"ACCC", acronym:"ACCC", fullName:"Australian Competition and Consumer Commission", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"National consumer watchdog. Takes action on misleading conduct, unconscionable behaviour and product safety.", whatTheyDo:"Enforces the Australian Consumer Law, investigates misleading advertising and anti-competitive behaviour.", useThisWhen:["A business gave you false or misleading information","You have a defective product and the seller won't help","Unfair contract terms were imposed on you"], handles:["Misleading conduct","Product safety","Unfair contracts","Consumer law breaches"], referralType:"Self-refer", phone:"1300 302 502", website:"https://www.accc.gov.au", emergency:false, tags:["Consumer","National"] },

  { id:"commonwealth-ombudsman", name:"Commonwealth Ombudsman", acronym:"Commonwealth Ombudsman", fullName:"Office of the Commonwealth Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"National", state:"National", description:"Investigates complaints about Australian Government agencies including Centrelink, ATO, NDIA and Australia Post.", whatTheyDo:"Handles complaints about federal government agencies' decisions and actions. Free and independent.", useThisWhen:["A federal government agency treated you unfairly","Centrelink or the ATO made an incorrect decision","A government decision appears wrong or unreasonable"], handles:["Centrelink complaints","ATO disputes","Home Affairs complaints","Australia Post issues"], referralType:"Self-refer", phone:"1300 362 072", website:"https://www.ombudsman.gov.au", emergency:false, tags:["Government","National"] },

  { id:"oaic", name:"OAIC", acronym:"OAIC", fullName:"Office of the Australian Information Commissioner", category:"Government Complaints", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Handles privacy complaints and freedom of information requests about federal agencies and large private organisations.", whatTheyDo:"Investigates breaches of the Privacy Act and handles FOI complaints.", useThisWhen:["Your personal information was mishandled or shared without consent","You were denied access to your own records","A government agency breached the Privacy Act"], handles:["Privacy complaints","FOI requests","Data breaches"], referralType:"Self-refer", phone:"1300 363 992", website:"https://www.oaic.gov.au", emergency:false, tags:["Privacy","FOI","National"] },

  { id:"acma", name:"ACMA", acronym:"ACMA", fullName:"Australian Communications and Media Authority", category:"Telecommunications", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Regulates broadcasting, internet, radio and telecommunications in Australia.", whatTheyDo:"Enforces the Telecommunications Consumer Protections Code and handles spam and scam call complaints.", useThisWhen:["Your telco is breaching consumer protection rules","You are receiving spam calls or messages","TIO has not resolved your issue"], handles:["Spam complaints","Telco regulation","Broadcasting complaints"], referralType:"Self-refer", phone:"1300 850 115", website:"https://www.acma.gov.au", emergency:false, tags:["Telco","Media","National"] },

  { id:"tio", name:"TIO", acronym:"TIO", fullName:"Telecommunications Industry Ombudsman", category:"Telecommunications", serviceType:"Ombudsman", jurisdiction:"National", state:"National", description:"Free, independent complaints service for unresolved phone and internet disputes.", whatTheyDo:"Investigates complaints about telcos when they haven't resolved your issue within 10 business days.", useThisWhen:["Your telco hasn't fixed your complaint in 10 business days","You are being billed for a service you don't have","Your internet or phone is not working as promised"], handles:["Mobile complaints","Internet disputes","Billing errors","Contract disputes"], referralType:"Self-refer", phone:"1800 062 058", website:"https://www.tio.com.au", emergency:false, tags:["Telco","Internet","National"] },

  { id:"esafety", name:"eSafety Commissioner", acronym:"eSafety", fullName:"Office of the eSafety Commissioner", category:"Telecommunications", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Australia's online safety regulator. Helps remove harmful online content including cyberbullying and image-based abuse.", whatTheyDo:"Investigates online abuse and requires platforms to remove harmful content.", useThisWhen:["You are being cyberbullied or harassed online","Someone shared intimate images without your consent","A child is being targeted online"], handles:["Cyberbullying","Image-based abuse","Online harassment","Child online safety"], referralType:"Self-refer", phone:"1800 686 428", website:"https://www.esafety.gov.au", emergency:false, tags:["Online Safety","National"] },

  { id:"aer", name:"AER", acronym:"AER", fullName:"Australian Energy Regulator", category:"Utilities", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Regulates electricity and gas markets nationally and protects energy consumers.", whatTheyDo:"Enforces energy consumer protection rules and investigates systemic issues.", useThisWhen:["Your energy retailer isn't following consumer protection rules","State energy ombudsman cannot help"], handles:["Energy market regulation","Consumer protection breaches"], referralType:"Self-refer", phone:"1300 585 165", website:"https://www.aer.gov.au", emergency:false, tags:["Energy","National"] },

  { id:"afsa", name:"AFSA", acronym:"AFSA", fullName:"Australian Financial Security Authority", category:"Banking & Finance", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Administers personal insolvency and bankruptcy in Australia.", whatTheyDo:"Manages bankruptcy and debt agreements. Investigates trustee conduct.", useThisWhen:["You are considering bankruptcy","A trustee is acting improperly","You need to understand insolvency options"], handles:["Bankruptcy","Debt agreements","Insolvency"], referralType:"Self-refer", phone:"1300 364 785", website:"https://www.afsa.gov.au", emergency:false, tags:["Finance","Debt","National"] },

  { id:"ndis-commission", name:"NDIS Commission", acronym:"NDIS Commission", fullName:"NDIS Quality and Safeguards Commission", category:"Disability / NDIS", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Handles complaints about NDIS providers and workers. Protects participant rights and safety.", whatTheyDo:"Investigates complaints about the quality and safety of NDIS supports and services.", useThisWhen:["An NDIS provider is not delivering supports as agreed","You were mistreated or neglected by a provider","A provider breached your rights"], handles:["NDIS provider complaints","Participant rights","Worker misconduct"], referralType:"Self-refer", phone:"1800 035 544", website:"https://www.ndiscommission.gov.au", emergency:false, tags:["NDIS","Disability","National"] },

  { id:"fair-work-ombudsman", name:"Fair Work Ombudsman", acronym:"FWO", fullName:"Fair Work Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"National", state:"National", description:"Investigates workplace rights, award underpayments and Fair Work Act breaches.", whatTheyDo:"Investigates underpayments, unlawful deductions and workplace rights breaches.", useThisWhen:["You were underpaid","Your employer is not following your award","You were denied leave entitlements"], handles:["Underpayment","Award breaches","Workplace rights"], referralType:"Self-refer", phone:"13 13 94", website:"https://www.fairwork.gov.au", emergency:false, tags:["Employment","National"] },

  { id:"fair-work-commission", name:"Fair Work Commission", acronym:"FWC", fullName:"Fair Work Commission", category:"Government Complaints", serviceType:"Tribunal", jurisdiction:"National", state:"National", description:"Handles unfair dismissal, general protections and workplace disputes.", whatTheyDo:"Adjudicates unfair dismissal applications and general protections claims.", useThisWhen:["You were unfairly dismissed","Your workplace rights were breached","Apply within 21 days of dismissal"], handles:["Unfair dismissal","General protections","Workplace disputes"], referralType:"Self-refer", phone:"1300 799 675", website:"https://www.fwc.gov.au", emergency:false, tags:["Employment","National"] },

  { id:"services-australia", name:"Services Australia", acronym:"Services Australia", fullName:"Services Australia Complaints", category:"Government Complaints", serviceType:"Government Complaints", jurisdiction:"National", state:"National", description:"Handles complaints about Centrelink, Medicare and Child Support services.", whatTheyDo:"Processes formal complaints about incorrect decisions, delays and poor service.", useThisWhen:["Centrelink made a decision you believe is wrong","You experienced unreasonable delays","A worker treated you poorly"], handles:["Centrelink complaints","Medicare disputes","Child Support issues"], referralType:"Self-refer", phone:"132 850", website:"https://www.servicesaustralia.gov.au/contact-us", emergency:false, tags:["Government","Centrelink","National"] },

  { id:"ahrc", name:"Australian Human Rights Commission", acronym:"AHRC", fullName:"Australian Human Rights Commission", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"National", state:"National", description:"Handles complaints about discrimination, harassment and human rights under federal law.", whatTheyDo:"Investigates discrimination based on race, sex, disability, age and other grounds.", useThisWhen:["You were discriminated against at work or in housing","You were sexually harassed","You experienced racial or disability discrimination"], handles:["Racial discrimination","Sex discrimination","Disability discrimination","Age discrimination"], referralType:"Self-refer", phone:"1300 656 419", website:"https://humanrights.gov.au/complaints", emergency:false, tags:["Human Rights","Discrimination","National"] },

  { id:"ahpra", name:"AHPRA", acronym:"AHPRA", fullName:"Australian Health Practitioner Regulation Agency", category:"Health Complaints", serviceType:"Regulator", jurisdiction:"National", state:"National", description:"Handles complaints about registered health practitioners including doctors, nurses and dentists.", whatTheyDo:"Investigates complaints about registered health practitioners' conduct and competence.", useThisWhen:["A doctor, nurse or dentist treated you unsafely","A health practitioner acted unprofessionally"], handles:["Medical complaints","Nursing complaints","Dental complaints"], referralType:"Self-refer", phone:"1300 419 495", website:"https://www.ahpra.gov.au/notifications", emergency:false, tags:["Health","National"] },

  { id:"ndia", name:"NDIA", acronym:"NDIA", fullName:"National Disability Insurance Agency", category:"Disability / NDIS", serviceType:"Disability Support", jurisdiction:"National", state:"National", description:"Manages the NDIS. Handles plan decisions and access reviews.", whatTheyDo:"Manages NDIS plans, access decisions and funding. Handles internal review requests.", useThisWhen:["Your NDIS access was denied","Your NDIS plan funding is insufficient","You want an internal review"], handles:["NDIS plan disputes","Access decisions","Funding reviews"], referralType:"Self-refer", phone:"1800 800 110", website:"https://www.ndis.gov.au/contact/complaints", emergency:false, tags:["NDIS","Disability","National"] },

  // ── NATIONAL SUPPORT / ADVOCACY ───────────────────────────────────────────

  { id:"ask-izzy", name:"Ask Izzy", acronym:"Ask Izzy", fullName:"Ask Izzy", category:"Housing / Homelessness", serviceType:"Referral Service", jurisdiction:"National", state:"National", description:"Online referral directory for housing, food, health, legal help, money, family violence and emergency support across Australia.", whatTheyDo:"Connects people with local support services. Works on any device, even with no data credit.", useThisWhen:["You are homeless or at risk","You need food, shelter or emergency supplies","You are fleeing domestic violence"], handles:["Housing referrals","Food assistance","Emergency support","DV referrals"], referralType:"Self-refer", phone:"", website:"https://askizzy.org.au", emergency:true, tags:["Housing","Emergency","National"] },

  { id:"national-debt-helpline", name:"National Debt Helpline", acronym:"NDH", fullName:"National Debt Helpline", category:"Banking & Finance", serviceType:"Financial Counselling", jurisdiction:"National", state:"National", description:"Free financial counselling for people struggling with debt, bills, repayments or financial hardship.", whatTheyDo:"Connects callers with free, independent financial counsellors.", useThisWhen:["You cannot afford loan repayments","You are being chased for debt","Your power, phone or rent is at risk","You need hardship options"], handles:["Debt counselling","Financial hardship","Credit defaults","Repayment plans"], referralType:"Self-refer", phone:"1800 007 007", website:"https://ndh.org.au", emergency:false, tags:["Finance","Debt","Hardship","National"] },

  { id:"financial-counselling-australia", name:"Financial Counselling Australia", acronym:"FCA", fullName:"Financial Counselling Australia", category:"Banking & Finance", serviceType:"Financial Counselling", jurisdiction:"National", state:"National", description:"Peak body for financial counsellors. Provides referrals to free financial counselling services nationwide.", whatTheyDo:"Connects consumers with qualified financial counsellors for debt and hardship help.", useThisWhen:["You need a financial counsellor near you","You are in financial hardship"], handles:["Financial counselling referrals","Hardship assistance","Debt management"], referralType:"Self-refer", phone:"1800 007 007", website:"https://www.financialcounsellingaustralia.org.au", emergency:false, tags:["Finance","Hardship","National"] },

  { id:"consumer-action", name:"Consumer Action Law Centre", acronym:"CALC", fullName:"Consumer Action Law Centre", category:"Consumer Rights", serviceType:"Advocacy Service", jurisdiction:"National", state:"VIC", description:"Legal advocacy and policy work on behalf of consumers.", whatTheyDo:"Provides consumer legal advice for Victorians and national policy support on credit, utilities, insurance and debt.", useThisWhen:["You need legal help with a consumer dispute in VIC","You have a credit or insurance problem","Facing debt collection pressure"], handles:["Consumer law","Credit disputes","Insurance complaints","Debt issues"], referralType:"Self-refer", phone:"1800 466 477", website:"https://consumeraction.org.au", emergency:false, tags:["Consumer","Legal","National","VIC"] },

  { id:"community-legal-centres-australia", name:"Community Legal Centres Australia", acronym:"CLCA", fullName:"Community Legal Centres Australia", category:"Legal Help", serviceType:"Community Legal Centre", jurisdiction:"National", state:"National", description:"Peak body. Helps people find free legal help near them.", whatTheyDo:"Refers people to their nearest community legal centre for free legal advice.", useThisWhen:["You cannot afford private legal advice","You need help before court","You need the right legal service"], handles:["Legal referrals","Tenancy","Debt","Family law"], referralType:"Self-refer", phone:"02 9264 9595", website:"https://clcs.org.au", emergency:false, tags:["Legal","National"] },

  { id:"justice-connect", name:"Justice Connect", acronym:"Justice Connect", fullName:"Justice Connect", category:"Legal Help", serviceType:"Community Legal Centre", jurisdiction:"National", state:"National", description:"Free legal help for people who cannot afford it — homelessness law, refugee law and not-for-profits.", whatTheyDo:"Connects people with free legal advice for homelessness, refugee and community organisations.", useThisWhen:["You are homeless and need legal help","You are a refugee or asylum seeker"], handles:["Homeless law","Refugee law","Tenancy"], referralType:"Self-refer", phone:"03 8636 4400", website:"https://justiceconnect.org.au", emergency:false, tags:["Legal","Housing","National"] },

  { id:"homelessness-australia", name:"Homelessness Australia", acronym:"Homelessness Australia", fullName:"Homelessness Australia", category:"Housing / Homelessness", serviceType:"Housing Support", jurisdiction:"National", state:"National", description:"National peak body for homelessness services.", whatTheyDo:"Advocates for homelessness services and provides referrals to housing support.", useThisWhen:["You need homelessness support services","You are at risk of losing housing"], handles:["Housing referrals","Homelessness advocacy"], referralType:"Referral", phone:"02 6247 4580", website:"https://www.homelessnessaustralia.org.au", emergency:false, tags:["Housing","Homelessness","National"] },

  { id:"1800respect", name:"1800RESPECT", acronym:"1800RESPECT", fullName:"1800RESPECT — National Domestic Violence Counselling", category:"Domestic Violence / Safety", serviceType:"Crisis Support", jurisdiction:"National", state:"National", description:"24/7 national sexual assault, family and domestic violence counselling. Confidential. Free.", whatTheyDo:"Provides trauma-informed counselling, safety planning and referrals for DV situations.", useThisWhen:["You are experiencing family or domestic violence","You need safety planning","You need DV referrals"], handles:["DV counselling","Safety planning","Crisis referrals"], referralType:"Self-refer", phone:"1800 737 732", website:"https://www.1800respect.org.au", emergency:true, tags:["DV","Safety","Crisis","National"] },

  { id:"lifeline", name:"Lifeline", acronym:"Lifeline", fullName:"Lifeline Australia", category:"Domestic Violence / Safety", serviceType:"Crisis Support", jurisdiction:"National", state:"National", description:"24/7 crisis support and suicide prevention.", whatTheyDo:"Provides crisis support, emotional assistance and referrals.", useThisWhen:["You are in emotional crisis","You need immediate mental health support"], handles:["Crisis counselling","Suicide prevention"], referralType:"Self-refer", phone:"13 11 14", website:"https://www.lifeline.org.au", emergency:true, tags:["Crisis","Mental Health","National"] },

  { id:"beyondblue", name:"Beyond Blue", acronym:"Beyond Blue", fullName:"Beyond Blue", category:"Domestic Violence / Safety", serviceType:"Crisis Support", jurisdiction:"National", state:"National", description:"Mental health support, information and referrals for anxiety and depression.", whatTheyDo:"Provides mental health information, forums and counselling referrals.", useThisWhen:["You are struggling with anxiety or depression","You need mental health support"], handles:["Mental health support","Anxiety and depression"], referralType:"Self-refer", phone:"1300 224 636", website:"https://www.beyondblue.org.au", emergency:false, tags:["Mental Health","National"] },

  { id:"disability-gateway", name:"Disability Gateway", acronym:"Disability Gateway", fullName:"Disability Gateway", category:"Disability / NDIS", serviceType:"Disability Support", jurisdiction:"National", state:"National", description:"National gateway to disability services. Helps find the right supports.", whatTheyDo:"Connects people with disability to information and services including NDIS and housing.", useThisWhen:["You need disability services near you","You need NDIS information"], handles:["Disability referrals","NDIS information"], referralType:"Self-refer", phone:"1800 643 787", website:"https://www.disabilitygateway.gov.au", emergency:false, tags:["Disability","NDIS","National"] },

  { id:"opan", name:"OPAN", acronym:"OPAN", fullName:"Older Persons Advocacy Network", category:"Disability / NDIS", serviceType:"Advocacy Service", jurisdiction:"National", state:"National", description:"Free independent advocacy for people receiving or seeking aged care services.", whatTheyDo:"Helps older Australians understand and exercise their rights in aged care.", useThisWhen:["You are unhappy with your aged care provider","You believe your aged care rights were not respected"], handles:["Aged care advocacy","Rights information"], referralType:"Self-refer", phone:"1800 700 600", website:"https://opan.org.au", emergency:false, tags:["Aged Care","Disability","National"] },

  { id:"carer-gateway", name:"Carer Gateway", acronym:"Carer Gateway", fullName:"Carer Gateway", category:"Disability / NDIS", serviceType:"Referral Service", jurisdiction:"National", state:"National", description:"Government-funded service for carers. Practical support, counselling and referrals.", whatTheyDo:"Connects carers with respite, peer support, financial assistance and practical help.", useThisWhen:["You are caring for a person with disability or illness","You need respite or carer support"], handles:["Carer support","Respite services","Financial help"], referralType:"Self-refer", phone:"1800 422 737", website:"https://www.carergateway.gov.au", emergency:false, tags:["Carer","Disability","National"] },

  // ── NSW ───────────────────────────────────────────────────────────────────

  { id:"ncat", name:"NCAT", acronym:"NCAT", fullName:"NSW Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"NSW", description:"Resolves tenancy disputes in NSW including rent, repairs, bond and eviction.", whatTheyDo:"Makes binding decisions on tenancy applications, bonds, repairs and termination disputes.", useThisWhen:["Your landlord refuses to do repairs","Your bond is being withheld unfairly","You received an unlawful eviction notice","You need a rent reduction order"], handles:["Tenancy disputes","Bond claims","Repair orders","Eviction challenges"], referralType:"Self-refer", phone:"1300 006 228", website:"https://www.ncat.nsw.gov.au", emergency:false, tags:["Tenancy","NSW"] },

  { id:"nsw-fair-trading", name:"NSW Fair Trading", acronym:"NSW Fair Trading", fullName:"NSW Fair Trading", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"NSW", description:"Consumer protection, product safety, building complaints and tenancy bond management in NSW.", whatTheyDo:"Handles consumer complaints, building disputes and manages rental bond accounts.", useThisWhen:["A business sold you a defective product","A builder hasn't completed work","You need to lodge or claim a rental bond"], handles:["Consumer complaints","Building disputes","Rental bonds"], referralType:"Self-refer", phone:"13 32 20", website:"https://www.fairtrading.nsw.gov.au", emergency:false, tags:["Consumer","Tenancy","NSW"] },

  { id:"nsw-ombudsman", name:"NSW Ombudsman", acronym:"NSW Ombudsman", fullName:"NSW Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"NSW", description:"Investigates complaints about NSW government agencies, community housing and child protection.", whatTheyDo:"Investigates maladministration and unfair conduct in NSW public agencies.", useThisWhen:["A NSW government agency treated you unfairly","You are unhappy with community housing decisions"], handles:["Government complaints","Community housing","Child protection"], referralType:"Self-refer", phone:"02 9286 1000", website:"https://www.ombo.nsw.gov.au", emergency:false, tags:["Government","NSW"] },

  { id:"legal-aid-nsw", name:"Legal Aid NSW", acronym:"Legal Aid NSW", fullName:"Legal Aid NSW", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"NSW", description:"Free legal advice and representation for eligible people in NSW.", whatTheyDo:"Provides legal advice, court representation and referrals for eligible NSW residents.", useThisWhen:["You need free legal advice in NSW","You are facing court","You need family law, tenancy or debt help"], handles:["Criminal law","Family law","Civil law","Tenancy","Debt"], referralType:"Self-refer", phone:"1300 888 529", website:"https://www.legalaid.nsw.gov.au", emergency:false, tags:["Legal","NSW"] },

  { id:"lawaccess-nsw", name:"LawAccess NSW", acronym:"LawAccess NSW", fullName:"LawAccess NSW", category:"Legal Help", serviceType:"Referral Service", jurisdiction:"State", state:"NSW", description:"Free government telephone service providing legal information and referrals in NSW.", whatTheyDo:"Provides legal information and connects callers with the right legal service.", useThisWhen:["You need to find legal help and don't know where to start","You have a legal question and need guidance"], handles:["Legal information","Referrals"], referralType:"Self-refer", phone:"1300 888 529", website:"https://www.lawaccess.nsw.gov.au", emergency:false, tags:["Legal","NSW"] },

  { id:"ewon", name:"EWON", acronym:"EWON", fullName:"Energy and Water Ombudsman NSW", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"NSW", description:"Free, independent dispute resolution for electricity, gas and water complaints in NSW.", whatTheyDo:"Investigates unresolved disputes with energy and water providers in NSW.", useThisWhen:["Your energy bill is incorrect and the retailer won't fix it","You are being wrongfully disconnected"], handles:["Electricity","Gas","Water billing","Disconnection"], referralType:"Self-refer", phone:"1800 246 545", website:"https://www.ewon.com.au", emergency:false, tags:["Energy","Water","NSW"] },

  { id:"hccc-nsw", name:"HCCC NSW", acronym:"HCCC", fullName:"Health Care Complaints Commission NSW", category:"Health Complaints", serviceType:"Health Complaints", jurisdiction:"State", state:"NSW", description:"Handles complaints about health practitioners and services in NSW.", whatTheyDo:"Investigates complaints about doctors, nurses, hospitals and other health providers in NSW.", useThisWhen:["A health practitioner treated you unsafely","You received inadequate medical care","A hospital caused you harm"], handles:["Medical complaints","Nursing complaints","Hospital complaints"], referralType:"Self-refer", phone:"1800 043 159", website:"https://www.hccc.nsw.gov.au", emergency:false, tags:["Health","NSW"] },

  { id:"anti-discrimination-nsw", name:"Anti-Discrimination NSW", acronym:"Anti-Discrimination NSW", fullName:"Anti-Discrimination NSW", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"NSW", description:"Handles complaints about unlawful discrimination and harassment in NSW.", whatTheyDo:"Investigates discrimination complaints in employment, education, housing and services.", useThisWhen:["You were discriminated against in NSW","You were sexually harassed at work"], handles:["Discrimination","Harassment","Vilification"], referralType:"Self-refer", phone:"1800 670 812", website:"https://www.antidiscrimination.nsw.gov.au", emergency:false, tags:["Discrimination","Human Rights","NSW"] },

  { id:"lecc-nsw", name:"LECC NSW", acronym:"LECC", fullName:"Law Enforcement Conduct Commission NSW", category:"Police / AVO / Court", serviceType:"Police Complaints", jurisdiction:"State", state:"NSW", description:"Investigates serious misconduct by NSW Police and the Crime Commission.", whatTheyDo:"Handles complaints about serious police misconduct and corruption in NSW.", useThisWhen:["NSW Police used excessive force","You believe a police officer acted corruptly"], handles:["Police misconduct","Corruption","Excessive force"], referralType:"Self-refer", phone:"1800 657 079", website:"https://www.lecc.nsw.gov.au", emergency:false, tags:["Police","NSW"] },

  { id:"nsw-victims-services", name:"NSW Victims Services", acronym:"NSW Victims Services", fullName:"NSW Victims Services", category:"Police / AVO / Court", serviceType:"Court Support", jurisdiction:"State", state:"NSW", description:"Supports victims of violent crime in NSW. Counselling, financial assistance and justice system support.", whatTheyDo:"Provides financial support, counselling and justice navigation for victims of violent crime.", useThisWhen:["You are a victim of violent crime","You need help navigating courts","You need counselling after a crime"], handles:["Victim support","Financial assistance","Court navigation"], referralType:"Self-refer", phone:"1800 633 063", website:"https://www.victimsservices.justice.nsw.gov.au", emergency:false, tags:["Victims","Court","NSW"] },

  { id:"tenants-union-nsw", name:"Tenants' Union NSW", acronym:"Tenants' Union NSW", fullName:"Tenants' Union of NSW", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"NSW", description:"Provides tenancy advocacy, resources and referrals for NSW renters.", whatTheyDo:"Offers free tenancy advice, guides renters through NCAT and advocates for better tenancy laws.", useThisWhen:["Your landlord refuses repairs","Your bond is being held unfairly","You received an eviction notice","You need tenancy rights help"], handles:["Tenancy advice","Bond disputes","Repairs","NCAT support"], referralType:"Self-refer", phone:"02 8117 3700", website:"https://www.tenants.org.au", emergency:false, tags:["Tenancy","NSW"] },

  { id:"women-legal-nsw", name:"Women's Legal Service NSW", acronym:"Women's Legal NSW", fullName:"Women's Legal Service NSW", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"NSW", description:"Free legal advice to women on family law, domestic violence, housing and welfare.", whatTheyDo:"Advises women on AVOs, separation, child custody, tenancy and Centrelink in DV context.", useThisWhen:["You are experiencing domestic violence","You need AVO help","You need family law advice"], handles:["DV legal help","AVO applications","Family law"], referralType:"Self-refer", phone:"1800 801 501", website:"https://www.wlsnsw.org.au", emergency:true, tags:["DV","Legal","Women","NSW"] },

  { id:"aboriginal-legal-nsw", name:"Aboriginal Legal Service NSW/ACT", acronym:"ALS NSW/ACT", fullName:"Aboriginal Legal Service NSW/ACT", category:"Legal Help", serviceType:"Community Legal Centre", jurisdiction:"State", state:"NSW", description:"Free legal assistance for Aboriginal and Torres Strait Islander people in NSW and the ACT.", whatTheyDo:"Provides criminal, civil and family law services for Aboriginal communities.", useThisWhen:["You are Aboriginal or Torres Strait Islander and need legal help in NSW or ACT","You are facing criminal charges"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1800 765 767", website:"https://www.alsnswact.org.au", emergency:false, tags:["Legal","Aboriginal","NSW","ACT"] },

  { id:"seniors-rights-nsw", name:"Seniors Rights Service NSW", acronym:"Seniors Rights NSW", fullName:"Seniors Rights Service NSW", category:"Legal Help", serviceType:"Advocacy Service", jurisdiction:"State", state:"NSW", description:"Free legal advice and advocacy for seniors in NSW on tenancy, aged care and elder abuse.", whatTheyDo:"Provides legal advice, advocacy and education for older people and on elder abuse.", useThisWhen:["You are experiencing elder abuse","You need tenancy help as an older person","You need aged care complaint support"], handles:["Elder abuse","Aged care rights","Tenancy"], referralType:"Self-refer", phone:"1800 424 079", website:"https://www.seniorsrights.org.au", emergency:false, tags:["Legal","Aged Care","NSW"] },

  // ── VIC ───────────────────────────────────────────────────────────────────

  { id:"vcat", name:"VCAT", acronym:"VCAT", fullName:"Victorian Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"VIC", description:"Resolves residential tenancy disputes in Victoria including bond, repairs, rent and eviction.", whatTheyDo:"Makes binding orders on tenancy disputes, bond claims and repair requirements.", useThisWhen:["Your landlord refuses repairs in VIC","Your bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims","Repair orders","Eviction challenges"], referralType:"Self-refer", phone:"1300 018 228", website:"https://www.vcat.vic.gov.au", emergency:false, tags:["Tenancy","VIC"] },

  { id:"consumer-affairs-vic", name:"Consumer Affairs Victoria", acronym:"CAV", fullName:"Consumer Affairs Victoria", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"VIC", description:"Consumer protection, business licensing and tenancy regulation in Victoria.", whatTheyDo:"Enforces consumer laws, handles tenancy bonds and licensing complaints.", useThisWhen:["A business sold you a defective product in VIC","Your landlord is breaching tenancy laws"], handles:["Consumer complaints","Tenancy","Licensing"], referralType:"Self-refer", phone:"1300 558 181", website:"https://www.consumer.vic.gov.au", emergency:false, tags:["Consumer","Tenancy","VIC"] },

  { id:"victorian-ombudsman", name:"Victorian Ombudsman", acronym:"Victorian Ombudsman", fullName:"Victorian Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"VIC", description:"Investigates complaints about Victorian government agencies and local councils.", whatTheyDo:"Investigates unfair or improper conduct by VIC government agencies.", useThisWhen:["A VIC government agency treated you unfairly","A local council made an unreasonable decision"], handles:["Government complaints","Council complaints"], referralType:"Self-refer", phone:"1800 806 314", website:"https://www.ombudsman.vic.gov.au", emergency:false, tags:["Government","VIC"] },

  { id:"victoria-legal-aid", name:"Victoria Legal Aid", acronym:"VLA", fullName:"Victoria Legal Aid", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"VIC", description:"Free legal help for Victorians on criminal, family, civil and social security law.", whatTheyDo:"Provides legal advice, duty lawyer services and representation for eligible Victorians.", useThisWhen:["You need free legal advice in VIC","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1300 792 387", website:"https://www.legalaid.vic.gov.au", emergency:false, tags:["Legal","VIC"] },

  { id:"ewov", name:"EWOV", acronym:"EWOV", fullName:"Energy and Water Ombudsman Victoria", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"VIC", description:"Free dispute resolution for electricity, gas and water complaints in Victoria.", whatTheyDo:"Investigates unresolved disputes with energy and water providers in VIC.", useThisWhen:["Your energy bill is wrong in VIC","You face wrongful disconnection"], handles:["Electricity","Gas","Water billing"], referralType:"Self-refer", phone:"1800 500 509", website:"https://www.ewov.com.au", emergency:false, tags:["Energy","Water","VIC"] },

  { id:"veohrc", name:"VEOHRC", acronym:"VEOHRC", fullName:"Victorian Equal Opportunity and Human Rights Commission", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"VIC", description:"Handles discrimination and sexual harassment complaints under Victorian equal opportunity laws.", whatTheyDo:"Investigates discrimination and harassment in employment, education and services.", useThisWhen:["You were discriminated against in VIC","You were sexually harassed"], handles:["Discrimination","Sexual harassment"], referralType:"Self-refer", phone:"1300 292 153", website:"https://www.humanrightscommission.vic.gov.au", emergency:false, tags:["Discrimination","Human Rights","VIC"] },

  { id:"ibac-vic", name:"IBAC VIC", acronym:"IBAC", fullName:"Independent Broad-based Anti-corruption Commission VIC", category:"Police / AVO / Court", serviceType:"Police Complaints", jurisdiction:"State", state:"VIC", description:"Investigates corruption and serious misconduct by VIC public servants and Victoria Police.", whatTheyDo:"Handles serious police misconduct and corruption complaints in VIC.", useThisWhen:["Victoria Police used excessive force","A public servant acted corruptly"], handles:["Police misconduct","Corruption"], referralType:"Self-refer", phone:"1300 735 135", website:"https://www.ibac.vic.gov.au", emergency:false, tags:["Police","Corruption","VIC"] },

  { id:"tenants-victoria", name:"Tenants Victoria", acronym:"Tenants VIC", fullName:"Tenants Victoria", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"VIC", description:"Free tenancy advice and advocacy for renters in Victoria.", whatTheyDo:"Provides tenancy advice, helps renters at VCAT and advocates for better tenancy laws.", useThisWhen:["You need tenancy advice in VIC","Your landlord refuses repairs"], handles:["Tenancy advice","Bond disputes","VCAT support"], referralType:"Self-refer", phone:"03 9416 2577", website:"https://www.tenantsvic.org.au", emergency:false, tags:["Tenancy","VIC"] },

  { id:"womens-legal-vic", name:"Women's Legal Service VIC", acronym:"Women's Legal VIC", fullName:"Women's Legal Service Victoria", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"VIC", description:"Free legal advice for women in Victoria on domestic violence, family law and housing.", whatTheyDo:"Provides legal advice and advocacy for women experiencing family violence.", useThisWhen:["You are experiencing domestic violence in VIC","You need an intervention order"], handles:["DV legal help","Intervention orders","Family law"], referralType:"Self-refer", phone:"1800 133 302", website:"https://www.womenslegal.org.au", emergency:true, tags:["DV","Legal","Women","VIC"] },

  { id:"hcc-vic", name:"Health Complaints Commissioner VIC", acronym:"HCC VIC", fullName:"Health Complaints Commissioner Victoria", category:"Health Complaints", serviceType:"Health Complaints", jurisdiction:"State", state:"VIC", description:"Handles complaints about health services and providers in Victoria.", whatTheyDo:"Investigates complaints about health services, hospitals and practitioners in VIC.", useThisWhen:["You received inadequate healthcare in VIC","A hospital treated you poorly"], handles:["Health service complaints","Hospital complaints"], referralType:"Self-refer", phone:"1300 582 113", website:"https://www.hcc.vic.gov.au", emergency:false, tags:["Health","VIC"] },

  // ── QLD ───────────────────────────────────────────────────────────────────

  { id:"qcat", name:"QCAT", acronym:"QCAT", fullName:"Queensland Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"QLD", description:"Resolves residential tenancy disputes in Queensland.", whatTheyDo:"Makes binding decisions on tenancy, bond and repair matters in QLD.", useThisWhen:["Your landlord refuses repairs in QLD","Bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims","Repair orders"], referralType:"Self-refer", phone:"1300 753 228", website:"https://www.qcat.qld.gov.au", emergency:false, tags:["Tenancy","QLD"] },

  { id:"qld-fair-trading", name:"QLD Office of Fair Trading", acronym:"QLD OFT", fullName:"Queensland Office of Fair Trading", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"QLD", description:"Consumer protection, licensing and fair trading regulation in Queensland.", whatTheyDo:"Handles consumer complaints and licensing issues in QLD.", useThisWhen:["A business sold you a defective product in QLD"], handles:["Consumer complaints","Licensing"], referralType:"Self-refer", phone:"13 74 68", website:"https://www.qld.gov.au/law/fair-trading", emergency:false, tags:["Consumer","QLD"] },

  { id:"qld-ombudsman", name:"Queensland Ombudsman", acronym:"QLD Ombudsman", fullName:"Queensland Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"QLD", description:"Investigates complaints about QLD government agencies and public services.", whatTheyDo:"Investigates unfair decisions and actions by QLD government agencies.", useThisWhen:["A QLD government agency treated you unfairly"], handles:["Government complaints","Agency conduct"], referralType:"Self-refer", phone:"07 3005 7000", website:"https://www.ombudsman.qld.gov.au", emergency:false, tags:["Government","QLD"] },

  { id:"legal-aid-qld", name:"Legal Aid Queensland", acronym:"Legal Aid QLD", fullName:"Legal Aid Queensland", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"QLD", description:"Free legal advice and representation for eligible Queenslanders.", whatTheyDo:"Provides legal advice, court representation and duty lawyer services in QLD.", useThisWhen:["You need free legal help in QLD","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1300 651 188", website:"https://www.legalaid.qld.gov.au", emergency:false, tags:["Legal","QLD"] },

  { id:"ewoq", name:"EWOQ", acronym:"EWOQ", fullName:"Energy and Water Ombudsman Queensland", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"QLD", description:"Free dispute resolution for electricity, gas and water complaints in Queensland.", whatTheyDo:"Investigates unresolved energy and water disputes in QLD.", useThisWhen:["Your energy bill is wrong in QLD","You face wrongful disconnection"], handles:["Electricity","Gas","Water billing"], referralType:"Self-refer", phone:"1800 662 837", website:"https://www.ewoq.com.au", emergency:false, tags:["Energy","Water","QLD"] },

  { id:"qhrc", name:"Queensland Human Rights Commission", acronym:"QHRC", fullName:"Queensland Human Rights Commission", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"QLD", description:"Handles anti-discrimination and human rights complaints in Queensland.", whatTheyDo:"Investigates discrimination and harassment complaints in QLD.", useThisWhen:["You were discriminated against in QLD","You were sexually harassed at work"], handles:["Discrimination","Harassment","Human rights"], referralType:"Self-refer", phone:"07 3247 0981", website:"https://www.qhrc.qld.gov.au", emergency:false, tags:["Discrimination","Human Rights","QLD"] },

  { id:"ccc-qld", name:"CCC Queensland", acronym:"CCC QLD", fullName:"Crime and Corruption Commission Queensland", category:"Police / AVO / Court", serviceType:"Police Complaints", jurisdiction:"State", state:"QLD", description:"Investigates corruption and serious misconduct by QLD public servants and Police.", whatTheyDo:"Handles serious police misconduct and corruption in QLD.", useThisWhen:["QLD Police acted corruptly or used excessive force"], handles:["Police misconduct","Corruption"], referralType:"Self-refer", phone:"07 3360 6060", website:"https://www.ccc.qld.gov.au", emergency:false, tags:["Police","Corruption","QLD"] },

  { id:"tenants-qld", name:"Tenants Queensland", acronym:"Tenants QLD", fullName:"Tenants Queensland", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"QLD", description:"Free tenancy advice for renters in Queensland.", whatTheyDo:"Provides tenancy advice and helps renters understand their rights.", useThisWhen:["You need tenancy advice in QLD","Your bond is being withheld"], handles:["Tenancy advice","Bond disputes"], referralType:"Self-refer", phone:"1300 744 263", website:"https://tenantsqld.org.au", emergency:false, tags:["Tenancy","QLD"] },

  { id:"womens-legal-qld", name:"Women's Legal Service QLD", acronym:"Women's Legal QLD", fullName:"Women's Legal Service Queensland", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"QLD", description:"Free legal advice for women in Queensland on domestic violence and family law.", whatTheyDo:"Provides legal advice and court support for women affected by domestic violence in QLD.", useThisWhen:["You are experiencing domestic violence in QLD","You need a DVO"], handles:["DV legal help","Protection orders","Family law"], referralType:"Self-refer", phone:"07 3392 0670", website:"https://www.wlsq.org.au", emergency:true, tags:["DV","Legal","Women","QLD"] },

  { id:"oho-qld", name:"Health Ombudsman QLD", acronym:"OHO QLD", fullName:"Office of the Health Ombudsman Queensland", category:"Health Complaints", serviceType:"Health Complaints", jurisdiction:"State", state:"QLD", description:"Handles health practitioner and service complaints in Queensland.", whatTheyDo:"Investigates complaints about health practitioners and services in QLD.", useThisWhen:["A health practitioner treated you unsafely in QLD"], handles:["Health complaints","Practitioner conduct"], referralType:"Self-refer", phone:"133 646", website:"https://www.oho.qld.gov.au", emergency:false, tags:["Health","QLD"] },

  // ── SA ────────────────────────────────────────────────────────────────────

  { id:"sacat", name:"SACAT", acronym:"SACAT", fullName:"South Australian Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"SA", description:"Resolves residential tenancy disputes in South Australia.", whatTheyDo:"Makes binding decisions on tenancy, bond and repair disputes in SA.", useThisWhen:["Your landlord refuses repairs in SA","Bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims","Repair orders"], referralType:"Self-refer", phone:"1800 723 767", website:"https://www.sacat.sa.gov.au", emergency:false, tags:["Tenancy","SA"] },

  { id:"cbs-sa", name:"Consumer and Business Services SA", acronym:"CBS SA", fullName:"Consumer and Business Services South Australia", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"SA", description:"Consumer protection, tenancy bonds and licensing in SA.", whatTheyDo:"Handles consumer complaints and tenancy bond management in SA.", useThisWhen:["A business acted unfairly in SA","You need tenancy bond help"], handles:["Consumer complaints","Tenancy bonds","Licensing"], referralType:"Self-refer", phone:"131 882", website:"https://www.cbs.sa.gov.au", emergency:false, tags:["Consumer","Tenancy","SA"] },

  { id:"ombudsman-sa", name:"SA Ombudsman", acronym:"SA Ombudsman", fullName:"Ombudsman South Australia", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"SA", description:"Investigates complaints about SA government agencies.", whatTheyDo:"Investigates unfair or improper conduct by SA government agencies.", useThisWhen:["A SA government agency treated you unfairly"], handles:["Government complaints","Agency conduct"], referralType:"Self-refer", phone:"08 8226 8699", website:"https://www.ombudsman.sa.gov.au", emergency:false, tags:["Government","SA"] },

  { id:"legal-services-sa", name:"Legal Services Commission SA", acronym:"LSC SA", fullName:"Legal Services Commission South Australia", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"SA", description:"Free and subsidised legal services for eligible South Australians.", whatTheyDo:"Provides legal advice and court representation in SA.", useThisWhen:["You need free legal help in SA","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1300 366 424", website:"https://www.lsc.sa.gov.au", emergency:false, tags:["Legal","SA"] },

  { id:"ewosa", name:"EWOSA", acronym:"EWOSA", fullName:"Energy and Water Ombudsman South Australia", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"SA", description:"Free dispute resolution for energy and water complaints in SA.", whatTheyDo:"Investigates unresolved energy and water disputes in SA.", useThisWhen:["Your energy bill is wrong in SA","You face wrongful disconnection"], handles:["Electricity","Gas","Water billing"], referralType:"Self-refer", phone:"1800 665 565", website:"https://www.ewosa.com.au", emergency:false, tags:["Energy","Water","SA"] },

  { id:"equal-opportunity-sa", name:"Equal Opportunity SA", acronym:"EO SA", fullName:"Equal Opportunity Commission South Australia", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"SA", description:"Handles discrimination and harassment complaints under SA equal opportunity law.", whatTheyDo:"Investigates discrimination complaints in SA.", useThisWhen:["You were discriminated against in SA","You were sexually harassed at work in SA"], handles:["Discrimination","Harassment"], referralType:"Self-refer", phone:"08 8207 1977", website:"https://www.eoc.sa.gov.au", emergency:false, tags:["Discrimination","Human Rights","SA"] },

  { id:"shelter-sa", name:"Shelter SA", acronym:"Shelter SA", fullName:"Shelter SA", category:"Housing / Homelessness", serviceType:"Housing Support", jurisdiction:"State", state:"SA", description:"Housing advocacy and tenant support in South Australia.", whatTheyDo:"Advocates for affordable housing and provides tenancy support in SA.", useThisWhen:["You need housing support in SA","You are at risk of homelessness"], handles:["Housing advocacy","Tenancy support"], referralType:"Self-refer", phone:"08 8223 5155", website:"https://www.sheltersa.asn.au", emergency:false, tags:["Housing","Tenancy","SA"] },

  { id:"womens-legal-sa", name:"Women's Legal Service SA", acronym:"Women's Legal SA", fullName:"Women's Legal Service South Australia", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"SA", description:"Free legal advice for women in SA experiencing domestic violence and family law issues.", whatTheyDo:"Provides legal advice and advocacy for women affected by DV in SA.", useThisWhen:["You are experiencing domestic violence in SA","You need a restraining order"], handles:["DV legal help","Restraining orders","Family law"], referralType:"Self-refer", phone:"08 8221 5553", website:"https://www.wlssa.org.au", emergency:true, tags:["DV","Legal","Women","SA"] },

  // ── WA ────────────────────────────────────────────────────────────────────

  { id:"sat-wa", name:"State Administrative Tribunal WA", acronym:"SAT WA", fullName:"State Administrative Tribunal Western Australia", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"WA", description:"Resolves residential tenancy and civil disputes in Western Australia.", whatTheyDo:"Makes binding decisions on tenancy, licensing and civil disputes in WA.", useThisWhen:["Your landlord refuses repairs in WA","Bond is being withheld","You received an eviction notice in WA"], handles:["Tenancy disputes","Bond claims"], referralType:"Self-refer", phone:"1300 306 017", website:"https://www.sat.justice.wa.gov.au", emergency:false, tags:["Tenancy","WA"] },

  { id:"consumer-protection-wa", name:"Consumer Protection WA", acronym:"Consumer Protection WA", fullName:"Consumer Protection Western Australia", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"WA", description:"Consumer protection, tenancy and fair trading regulation in WA.", whatTheyDo:"Handles consumer complaints and tenancy bonds in WA.", useThisWhen:["A business sold you a defective product in WA","You need tenancy bond help in WA"], handles:["Consumer complaints","Tenancy bonds"], referralType:"Self-refer", phone:"1300 304 054", website:"https://www.consumerprotection.wa.gov.au", emergency:false, tags:["Consumer","Tenancy","WA"] },

  { id:"ombudsman-wa", name:"WA Ombudsman", acronym:"WA Ombudsman", fullName:"Ombudsman Western Australia", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"WA", description:"Investigates complaints about WA government agencies.", whatTheyDo:"Investigates unfair or improper conduct by WA government agencies.", useThisWhen:["A WA government agency treated you unfairly"], handles:["Government complaints"], referralType:"Self-refer", phone:"08 9220 7555", website:"https://www.ombudsman.wa.gov.au", emergency:false, tags:["Government","WA"] },

  { id:"legal-aid-wa", name:"Legal Aid WA", acronym:"Legal Aid WA", fullName:"Legal Aid Western Australia", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"WA", description:"Free legal services for eligible Western Australians.", whatTheyDo:"Provides legal advice and court representation in WA.", useThisWhen:["You need free legal help in WA","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1300 650 579", website:"https://www.legalaid.wa.gov.au", emergency:false, tags:["Legal","WA"] },

  { id:"ewowa", name:"EWOWA", acronym:"EWOWA", fullName:"Energy and Water Ombudsman Western Australia", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"WA", description:"Free dispute resolution for energy and water complaints in WA.", whatTheyDo:"Investigates unresolved energy and water disputes in WA.", useThisWhen:["Your energy bill is wrong in WA","You face wrongful disconnection"], handles:["Electricity","Gas","Water"], referralType:"Self-refer", phone:"1800 754 004", website:"https://www.ombudsman.wa.gov.au/energyandwater", emergency:false, tags:["Energy","Water","WA"] },

  { id:"eoc-wa", name:"Equal Opportunity Commission WA", acronym:"EOC WA", fullName:"Equal Opportunity Commission WA", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"WA", description:"Handles discrimination and harassment complaints under WA equal opportunity law.", whatTheyDo:"Investigates discrimination complaints in WA.", useThisWhen:["You were discriminated against in WA"], handles:["Discrimination","Harassment"], referralType:"Self-refer", phone:"08 9216 3900", website:"https://www.eoc.wa.gov.au", emergency:false, tags:["Discrimination","Human Rights","WA"] },

  { id:"ccc-wa", name:"CCC WA", acronym:"CCC WA", fullName:"Corruption and Crime Commission WA", category:"Police / AVO / Court", serviceType:"Police Complaints", jurisdiction:"State", state:"WA", description:"Investigates corruption and serious misconduct by WA public servants and Police.", whatTheyDo:"Handles serious police misconduct and corruption in WA.", useThisWhen:["WA Police acted corruptly or used excessive force"], handles:["Police misconduct","Corruption"], referralType:"Self-refer", phone:"08 9215 4888", website:"https://www.ccc.wa.gov.au", emergency:false, tags:["Police","Corruption","WA"] },

  { id:"tenancy-wa", name:"Tenancy WA", acronym:"Tenancy WA", fullName:"Tenancy WA", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"WA", description:"Free tenancy advice and advocacy for renters in WA.", whatTheyDo:"Provides tenancy advice and helps renters understand their rights.", useThisWhen:["You need tenancy advice in WA","Your landlord is not responding"], handles:["Tenancy advice","Bond disputes"], referralType:"Self-refer", phone:"08 9221 0088", website:"https://www.tenancywa.org.au", emergency:false, tags:["Tenancy","WA"] },

  { id:"womens-legal-wa", name:"Women's Legal Service WA", acronym:"Women's Legal WA", fullName:"Women's Legal Service WA", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"WA", description:"Free legal advice for women in WA experiencing domestic violence and family law issues.", whatTheyDo:"Provides legal advice for women affected by DV in WA.", useThisWhen:["You are experiencing domestic violence in WA","You need a violence restraining order"], handles:["DV legal help","Restraining orders","Family law"], referralType:"Self-refer", phone:"1800 625 122", website:"https://www.wlswa.org.au", emergency:true, tags:["DV","Legal","Women","WA"] },

  { id:"hadsco-wa", name:"HaDSCO WA", acronym:"HaDSCO", fullName:"Health and Disability Services Complaints Office WA", category:"Health Complaints", serviceType:"Health Complaints", jurisdiction:"State", state:"WA", description:"Health and disability service complaints in Western Australia.", whatTheyDo:"Investigates complaints about health and disability services in WA.", useThisWhen:["A health or disability service mistreated you in WA"], handles:["Health complaints","Disability service complaints"], referralType:"Self-refer", phone:"1800 813 583", website:"https://www.hadsco.wa.gov.au", emergency:false, tags:["Health","Disability","WA"] },

  // ── TAS ───────────────────────────────────────────────────────────────────

  { id:"tascat", name:"TASCAT", acronym:"TASCAT", fullName:"Tasmanian Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"TAS", description:"Resolves residential tenancy disputes in Tasmania.", whatTheyDo:"Makes binding decisions on tenancy and bond disputes in TAS.", useThisWhen:["Your landlord refuses repairs in TAS","Bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims"], referralType:"Self-refer", phone:"1300 001 164", website:"https://tascat.tas.gov.au", emergency:false, tags:["Tenancy","TAS"] },

  { id:"cbos-tas", name:"CBOS Tasmania", acronym:"CBOS TAS", fullName:"Consumer, Building and Occupational Services TAS", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"TAS", description:"Consumer protection, tenancy bonds and building regulation in TAS.", whatTheyDo:"Handles consumer complaints and tenancy bonds in TAS.", useThisWhen:["A business acted unfairly in TAS","You need tenancy bond help"], handles:["Consumer complaints","Tenancy bonds"], referralType:"Self-refer", phone:"1300 654 499", website:"https://www.cbos.tas.gov.au", emergency:false, tags:["Consumer","Tenancy","TAS"] },

  { id:"ombudsman-tas", name:"Ombudsman Tasmania", acronym:"TAS Ombudsman", fullName:"Ombudsman Tasmania", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"TAS", description:"Investigates complaints about TAS government agencies and public authorities.", whatTheyDo:"Investigates unfair or improper conduct by TAS government agencies.", useThisWhen:["A TAS government agency treated you unfairly"], handles:["Government complaints"], referralType:"Self-refer", phone:"1800 001 170", website:"https://www.ombudsman.tas.gov.au", emergency:false, tags:["Government","TAS"] },

  { id:"legal-aid-tas", name:"Legal Aid Tasmania", acronym:"Legal Aid TAS", fullName:"Legal Aid Commission of Tasmania", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"TAS", description:"Free legal advice and representation for eligible Tasmanians.", whatTheyDo:"Provides legal advice and court representation in TAS.", useThisWhen:["You need free legal help in TAS","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1300 366 611", website:"https://www.legalaid.tas.gov.au", emergency:false, tags:["Legal","TAS"] },

  { id:"energy-ombudsman-tas", name:"Energy Ombudsman Tasmania", acronym:"Energy Ombudsman TAS", fullName:"Ombudsman Tasmania – Energy", category:"Utilities", serviceType:"Ombudsman", jurisdiction:"State", state:"TAS", description:"Handles energy dispute resolution in Tasmania.", whatTheyDo:"Resolves unresolved electricity and gas disputes in TAS.", useThisWhen:["Your energy bill is wrong in TAS","You face disconnection in TAS"], handles:["Electricity","Gas"], referralType:"Self-refer", phone:"1800 001 170", website:"https://www.ombudsman.tas.gov.au", emergency:false, tags:["Energy","TAS"] },

  { id:"tenants-union-tas", name:"Tenants' Union Tasmania", acronym:"Tenants TAS", fullName:"Tenants' Union of Tasmania", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"TAS", description:"Free tenancy advice and advocacy for renters in Tasmania.", whatTheyDo:"Provides tenancy advice and tenant advocacy in TAS.", useThisWhen:["You need tenancy advice in TAS","Your bond is being withheld"], handles:["Tenancy advice","Bond disputes"], referralType:"Self-refer", phone:"1300 652 641", website:"https://www.tutas.org.au", emergency:false, tags:["Tenancy","TAS"] },

  // ── ACT ───────────────────────────────────────────────────────────────────

  { id:"acat", name:"ACAT", acronym:"ACAT", fullName:"ACT Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"ACT", description:"Resolves residential tenancy and civil disputes in the ACT.", whatTheyDo:"Makes binding decisions on tenancy and civil disputes in the ACT.", useThisWhen:["Your landlord refuses repairs in ACT","Bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims","Civil disputes"], referralType:"Self-refer", phone:"02 6207 1740", website:"https://www.acat.act.gov.au", emergency:false, tags:["Tenancy","ACT"] },

  { id:"access-canberra", name:"Access Canberra", acronym:"Access Canberra", fullName:"Access Canberra", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"ACT", description:"Consumer protection, licensing and fair trading in the ACT.", whatTheyDo:"Handles consumer complaints and tenancy bonds in the ACT.", useThisWhen:["A business acted unfairly in ACT","You need tenancy bond help"], handles:["Consumer complaints","Tenancy bonds","Licensing"], referralType:"Self-refer", phone:"13 22 81", website:"https://www.accesscanberra.act.gov.au", emergency:false, tags:["Consumer","Tenancy","ACT"] },

  { id:"act-ombudsman", name:"ACT Ombudsman", acronym:"ACT Ombudsman", fullName:"ACT Ombudsman", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"ACT", description:"Handles complaints about ACT government agencies.", whatTheyDo:"Investigates unfair or improper conduct by ACT government agencies.", useThisWhen:["An ACT government agency treated you unfairly"], handles:["Government complaints"], referralType:"Self-refer", phone:"1300 362 072", website:"https://www.ombudsman.gov.au", emergency:false, tags:["Government","ACT"] },

  { id:"legal-aid-act", name:"Legal Aid ACT", acronym:"Legal Aid ACT", fullName:"Legal Aid ACT", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"ACT", description:"Free legal advice and representation for eligible ACT residents.", whatTheyDo:"Provides legal advice and court representation in the ACT.", useThisWhen:["You need free legal help in ACT","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"02 6243 8197", website:"https://www.legalaidact.org.au", emergency:false, tags:["Legal","ACT"] },

  { id:"act-human-rights", name:"ACT Human Rights Commission", acronym:"ACT HRC", fullName:"ACT Human Rights Commission", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"ACT", description:"Handles discrimination and human rights complaints in the ACT.", whatTheyDo:"Investigates and conciliates discrimination and human rights complaints in ACT.", useThisWhen:["You were discriminated against in ACT","A public authority violated your rights"], handles:["Discrimination","Human rights"], referralType:"Self-refer", phone:"02 6205 2222", website:"https://hrc.act.gov.au", emergency:false, tags:["Discrimination","Human Rights","ACT"] },

  { id:"tenants-union-act", name:"Tenants' Union ACT", acronym:"Tenants ACT", fullName:"Tenants' Union ACT", category:"Tenancy & Housing", serviceType:"Tenancy Advice", jurisdiction:"State", state:"ACT", description:"Free tenancy advice and advocacy for renters in the ACT.", whatTheyDo:"Provides tenancy advice and helps ACT renters navigate disputes.", useThisWhen:["You need tenancy advice in ACT","Your bond is being withheld"], handles:["Tenancy advice","Bond disputes"], referralType:"Self-refer", phone:"02 6247 2011", website:"https://www.tenantsact.org.au", emergency:false, tags:["Tenancy","ACT"] },

  { id:"womens-legal-act", name:"Women's Legal Centre ACT", acronym:"Women's Legal ACT", fullName:"Women's Legal Centre ACT", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"ACT", description:"Free legal advice for women in the ACT on domestic violence and family law.", whatTheyDo:"Provides legal advice and advocacy for women affected by DV in ACT.", useThisWhen:["You are experiencing domestic violence in ACT","You need a protection order"], handles:["DV legal help","Protection orders","Family law"], referralType:"Self-refer", phone:"02 6257 4377", website:"https://www.wlc.org.au", emergency:true, tags:["DV","Legal","Women","ACT"] },

  // ── NT ────────────────────────────────────────────────────────────────────

  { id:"ntcat", name:"NTCAT", acronym:"NTCAT", fullName:"Northern Territory Civil and Administrative Tribunal", category:"Tenancy & Housing", serviceType:"Tribunal", jurisdiction:"State", state:"NT", description:"Resolves residential tenancy disputes in the Northern Territory.", whatTheyDo:"Makes binding decisions on tenancy, bond and repair disputes in the NT.", useThisWhen:["Your landlord refuses repairs in NT","Bond is being withheld","You received an eviction notice"], handles:["Tenancy disputes","Bond claims","Repair orders"], referralType:"Self-refer", phone:"1800 006 228", website:"https://ntcat.nt.gov.au", emergency:false, tags:["Tenancy","NT"] },

  { id:"consumer-affairs-nt", name:"Consumer Affairs NT", acronym:"Consumer Affairs NT", fullName:"Consumer Affairs Northern Territory", category:"Consumer Rights", serviceType:"Regulator", jurisdiction:"State", state:"NT", description:"Consumer protection, tenancy and fair trading in the NT.", whatTheyDo:"Handles consumer complaints and tenancy issues in the NT.", useThisWhen:["A business acted unfairly in NT","You need tenancy help"], handles:["Consumer complaints","Tenancy bonds"], referralType:"Self-refer", phone:"1800 019 319", website:"https://consumeraffairs.nt.gov.au", emergency:false, tags:["Consumer","Tenancy","NT"] },

  { id:"ombudsman-nt", name:"NT Ombudsman", acronym:"NT Ombudsman", fullName:"Ombudsman Northern Territory", category:"Government Complaints", serviceType:"Ombudsman", jurisdiction:"State", state:"NT", description:"Investigates complaints about NT government agencies.", whatTheyDo:"Investigates unfair or improper conduct by NT government agencies.", useThisWhen:["An NT government agency treated you unfairly"], handles:["Government complaints"], referralType:"Self-refer", phone:"1800 806 380", website:"https://ombudsman.nt.gov.au", emergency:false, tags:["Government","NT"] },

  { id:"legal-aid-nt", name:"NT Legal Aid", acronym:"NT Legal Aid", fullName:"NT Legal Aid Commission", category:"Legal Help", serviceType:"Legal Aid", jurisdiction:"State", state:"NT", description:"Free legal services for NT residents.", whatTheyDo:"Provides legal advice and court representation in the NT.", useThisWhen:["You need free legal help in NT","You are facing court"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1800 019 343", website:"https://www.ntlac.nt.gov.au", emergency:false, tags:["Legal","NT"] },

  { id:"utilities-commission-nt", name:"Utilities Commission NT", acronym:"Utilities Commission NT", fullName:"Utilities Commission NT", category:"Utilities", serviceType:"Regulator", jurisdiction:"State", state:"NT", description:"Regulates electricity, gas and water in the Northern Territory.", whatTheyDo:"Handles utility disputes and regulates energy and water in the NT.", useThisWhen:["You have an unresolved energy or water complaint in NT"], handles:["Electricity","Gas","Water"], referralType:"Self-refer", phone:"08 8999 6078", website:"https://utilitiescommission.nt.gov.au", emergency:false, tags:["Energy","Water","NT"] },

  { id:"nt-anti-discrimination", name:"NT Anti-Discrimination Commission", acronym:"NT ADC", fullName:"NT Anti-Discrimination Commission", category:"Human Rights / Discrimination", serviceType:"Human Rights", jurisdiction:"State", state:"NT", description:"Handles discrimination and harassment complaints in the NT.", whatTheyDo:"Investigates and conciliates discrimination complaints in the NT.", useThisWhen:["You were discriminated against in NT"], handles:["Discrimination","Harassment"], referralType:"Self-refer", phone:"1800 813 846", website:"https://adc.nt.gov.au", emergency:false, tags:["Discrimination","Human Rights","NT"] },

  { id:"naaja", name:"NAAJA", acronym:"NAAJA", fullName:"North Australian Aboriginal Justice Agency", category:"Legal Help", serviceType:"Community Legal Centre", jurisdiction:"State", state:"NT", description:"Free legal services for Aboriginal and Torres Strait Islander people in the NT.", whatTheyDo:"Provides criminal, civil and family law services for Aboriginal communities in the NT.", useThisWhen:["You are Aboriginal or Torres Strait Islander and need legal help in NT","You are facing criminal charges in NT"], handles:["Criminal law","Family law","Civil law"], referralType:"Self-refer", phone:"1800 898 251", website:"https://www.naaja.org.au", emergency:false, tags:["Legal","Aboriginal","NT"] },

  { id:"cawls", name:"Central Aus Women's Legal Service", acronym:"CAWLS", fullName:"Central Australian Women's Legal Service", category:"Domestic Violence / Safety", serviceType:"Community Legal Centre", jurisdiction:"State", state:"NT", description:"Free legal services for women in Central Australia for DV, family law and child protection.", whatTheyDo:"Provides free legal advice for women affected by violence in Central Australia.", useThisWhen:["You are experiencing domestic violence in Central Australia","You need a protection order in NT"], handles:["DV legal help","Protection orders","Family law"], referralType:"Self-refer", phone:"08 8953 0044", website:"https://www.cawls.org.au", emergency:true, tags:["DV","Legal","Women","NT"] },
];

// ─── Category hub cards shown on the directory landing ───────────────────────
export const CATEGORY_HUBS = [
  { id:"banking", emoji:"🏦", title:"Banking & Finance", tagline:"Banks, insurance, super, debt and hardship", who:["AFCA","ASIC","National Debt Helpline"], for:["Chargebacks & unauthorised transactions","Unfair bank fees","Insurance claim denials","Financial hardship & debt"] },
  { id:"tenancy", emoji:"🏠", title:"Tenancy & Housing", tagline:"Rentals, bonds, repairs, evictions, homelessness", who:["NCAT","VCAT","Tenants' Unions"], for:["Bond disputes","Landlord refuses repairs","Unlawful eviction notice","Homelessness & crisis housing"] },
  { id:"utilities", emoji:"⚡", title:"Energy & Utilities", tagline:"Electricity, gas, water billing and disconnection", who:["AER","EWON","EWOV","EWOQ"], for:["Incorrect bills","Wrongful disconnection","Meter errors","Service reliability"] },
  { id:"telco", emoji:"📱", title:"Telecommunications", tagline:"Phone, internet, mobile and broadband", who:["TIO","ACMA"], for:["No service","Billing errors","Misleading contracts","Device repair refusals"] },
  { id:"legal", emoji:"⚖️", title:"Legal Help", tagline:"Free legal advice, representation and court support", who:["Legal Aid","Community Legal Centres","LawAccess"], for:["Cannot afford a lawyer","Need advice before court","Tenancy or debt legal help","Family law issues"] },
  { id:"government", emoji:"🏛️", title:"Government Complaints", tagline:"Federal and state agency complaints", who:["Commonwealth Ombudsman","Services Australia","State Ombudsmen"], for:["Centrelink payment errors","ATO disputes","Government agency unfair conduct","Visa issues"] },
  { id:"health", emoji:"🏥", title:"Health Complaints", tagline:"Doctors, hospitals and Medicare", who:["AHPRA","HCCC","Health Ombudsmen"], for:["Unsafe medical care","Hospital complaints","Medicare billing disputes","Practitioner misconduct"] },
  { id:"disability", emoji:"♿", title:"Disability / NDIS", tagline:"NDIS, participant rights and disability services", who:["NDIS Commission","NDIA","Disability Gateway"], for:["NDIS plan denied or cut","Provider mistreatment","NDIS access issues","Disability service complaints"] },
  { id:"human-rights", emoji:"🛡️", title:"Human Rights / Discrimination", tagline:"Race, sex, disability and age discrimination", who:["AHRC","State Equal Opportunity bodies"], for:["Discrimination at work or housing","Sexual harassment","Racial vilification","Age discrimination"] },
  { id:"dv", emoji:"🆘", title:"Domestic Violence / Safety", tagline:"Crisis support, legal help and safety planning", who:["1800RESPECT","Women's Legal Services","Lifeline"], for:["Experiencing family violence","Need safety planning","AVO or protection order","Emergency housing"] },
  { id:"consumer", emoji:"🛒", title:"Consumer Rights", tagline:"Products, services, refunds and fair trading", who:["ACCC","Fair Trading bodies","Consumer Action"], for:["Defective products","Refusal to refund","Misleading advertising","Unfair contracts"] },
  { id:"police", emoji:"🚨", title:"Police / Court / AVO", tagline:"Police complaints, court support and victim services", who:["LECC","IBAC","Victims Services"], for:["Police misconduct or excessive force","AVO help","Navigating court as a victim","Corruption complaints"] },
];