import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { FileText, Sparkles, Loader2, CheckCircle2, AlertCircle } from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";

export default function ExecutiveSummaryGenerator({ caseItem }) {
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);
  const [summary, setSummary] = useState(null);
  const [showDialog, setShowDialog] = useState(false);

  const handleGenerateSummary = async () => {
    setGenerating(true);
    try {
      const response = await base44.functions.invoke('generateExecutiveSummary', {
        caseId: caseItem.id
      });

      if (response.data.success) {
        setSummary(response.data);
        setShowDialog(true);
        toast({
          title: "Executive Summary Generated",
          description: "AI has created a one-page summary of your case.",
        });
      }
    } catch (error) {
      toast({
        title: "Generation Failed",
        description: error.message || "Failed to generate summary. Please try again.",
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    if (!summary) return;

    const html = `
      <div style="font-family:'Times New Roman',Times,serif;font-size:12pt;color:#000;line-height:1.6;max-width:800px;margin:0 auto;padding:40px;">
        <h1 style="font-size:18pt;font-weight:bold;margin-bottom:8pt;color:#1e40af;">Executive Summary</h1>
        <h2 style="font-size:14pt;font-style:italic;margin-bottom:20pt;color:#374151;">${caseItem.title}</h2>
        
        <div style="background:#f3f4f6;padding:16pt;border-radius:6pt;margin-bottom:20pt;">
          <p style="font-size:11pt;line-height:1.8;white-space:pre-wrap;">${summary.summary}</p>
        </div>

        ${summary.key_issues && summary.key_issues.length > 0 ? `
          <h3 style="font-size:13pt;font-weight:bold;margin-top:16pt;margin-bottom:8pt;color:#1e40af;">Key Issues</h3>
          <ul style="margin-bottom:16pt;">
            ${summary.key_issues.map(issue => `<li style="font-size:11pt;margin-bottom:4pt;">${issue}</li>`).join('')}
          </ul>
        ` : ''}

        ${summary.evidence_highlights && summary.evidence_highlights.length > 0 ? `
          <h3 style="font-size:13pt;font-weight:bold;margin-top:16pt;margin-bottom:8pt;color:#1e40af;">Evidence Highlights</h3>
          <ul style="margin-bottom:16pt;">
            ${summary.evidence_highlights.map(ev => `<li style="font-size:11pt;margin-bottom:4pt;">${ev}</li>`).join('')}
          </ul>
        ` : ''}

        ${summary.next_steps && summary.next_steps.length > 0 ? `
          <h3 style="font-size:13pt;font-weight:bold;margin-top:16pt;margin-bottom:8pt;color:#1e40af;">Next Steps</h3>
          <ul style="margin-bottom:16pt;">
            ${summary.next_steps.map(step => `<li style="font-size:11pt;margin-bottom:4pt;">${step}</li>`).join('')}
          </ul>
        ` : ''}

        ${summary.critical_deadlines && summary.critical_deadlines.length > 0 ? `
          <h3 style="font-size:13pt;font-weight:bold;margin-top:16pt;margin-bottom:8pt;color:#dc2626;">Critical Deadlines</h3>
          <ul style="margin-bottom:16pt;">
            ${summary.critical_deadlines.map(dl => `<li style="font-size:11pt;margin-bottom:4pt;">${dl}</li>`).join('')}
          </ul>
        ` : ''}

        <div style="margin-top:30pt;padding-top:16pt;border-top:1pt solid #e5e7eb;font-size:9pt;color:#6b7280;">
          <p>Generated by Chaos Controller AI · ${new Date().toLocaleDateString('en-AU')}</p>
          <p>Case: ${caseItem.title} | Organisation: ${caseItem.organisation_name || 'N/A'}</p>
        </div>
      </div>
    `;

    if (!document.getElementById("cc-exec-summary-print-style")) {
      const s = document.createElement("style");
      s.id = "cc-exec-summary-print-style";
      s.innerHTML = `@media print { body * { visibility:hidden !important; } #cc-exec-summary-print, #cc-exec-summary-print * { visibility:visible !important; } #cc-exec-summary-print { position:fixed;left:0;top:0;width:100%; } @page { margin:2cm; } }`;
      document.head.appendChild(s);
    }
    let area = document.getElementById("cc-exec-summary-print");
    if (!area) { area = document.createElement("div"); area.id = "cc-exec-summary-print"; document.body.appendChild(area); }
    area.innerHTML = html;
    window.print();
  };

  return (
    <>
      <Button
        onClick={handleGenerateSummary}
        disabled={generating}
        className="gap-2 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 text-white font-bold"
      >
        {generating ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Generating...
          </>
        ) : (
          <>
            <Sparkles className="w-4 h-4" />
            AI Executive Summary
          </>
        )}
      </Button>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Executive Summary — {caseItem.title}
            </DialogTitle>
            <DialogDescription>
              AI-generated one-page summary for quick review
            </DialogDescription>
          </DialogHeader>

          {summary && (
            <div className="space-y-6 py-4">
              {/* Summary Text */}
              <div className="bg-gradient-to-r from-purple-50 to-indigo-50 dark:from-purple-950/20 dark:to-indigo-950/20 border border-purple-200 dark:border-purple-800 rounded-xl p-5">
                <h4 className="text-sm font-bold text-purple-900 dark:text-purple-300 mb-3 flex items-center gap-2">
                  <Sparkles className="w-4 h-4" />
                  Case Overview
                </h4>
                <p className="text-sm text-gray-800 dark:text-gray-200 leading-relaxed whitespace-pre-wrap">
                  {summary.summary}
                </p>
              </div>

              {/* Key Issues */}
              {summary.key_issues && summary.key_issues.length > 0 && (
                <div>
                  <h4 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-warning" />
                    Key Issues
                  </h4>
                  <ul className="space-y-2">
                    {summary.key_issues.map((issue, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <CheckCircle2 className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                        <span className="text-foreground">{issue}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Evidence Highlights */}
              {summary.evidence_highlights && summary.evidence_highlights.length > 0 && (
                <div>
                  <h4 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
                    <FileText className="w-4 h-4 text-accent" />
                    Evidence Highlights
                  </h4>
                  <ul className="space-y-2">
                    {summary.evidence_highlights.map((ev, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <CheckCircle2 className="w-4 h-4 text-accent shrink-0 mt-0.5" />
                        <span className="text-foreground">{ev}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Next Steps */}
              {summary.next_steps && summary.next_steps.length > 0 && (
                <div>
                  <h4 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-success" />
                    Next Steps
                  </h4>
                  <ul className="space-y-2">
                    {summary.next_steps.map((step, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
                        <span className="text-foreground">{step}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Critical Deadlines */}
              {summary.critical_deadlines && summary.critical_deadlines.length > 0 && (
                <div className="bg-destructive/10 border border-destructive/30 rounded-xl p-4">
                  <h4 className="text-sm font-bold text-destructive mb-3 flex items-center gap-2">
                    <AlertCircle className="w-4 h-4" />
                    Critical Deadlines
                  </h4>
                  <ul className="space-y-2">
                    {summary.critical_deadlines.map((dl, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <AlertCircle className="w-4 h-4 text-destructive shrink-0 mt-0.5" />
                        <span className="text-foreground font-medium">{dl}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setShowDialog(false)}>
              Close
            </Button>
            <Button onClick={handlePrint} className="gap-2">
              <FileText className="w-4 h-4" />
              Print Summary
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}