import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, FileText, Shield, Zap, Star, CheckCircle2, Lock } from "lucide-react";
import { motion } from "framer-motion";

const TIER_SAMPLES = [
  {
    tier: "Starter",
    price: "$25.00/mo",
    color: "#3B82F6",
    icon: FileText,
    description: "See a real 1st Complaint Letter generated by our AI for a banking dispute.",
    letter_title: "1st Formal Complaint Letter — Banking",
    letter: `To the Complaints Manager,
Commonwealth Bank of Australia
GPO Box 9925, Sydney NSW 2001

Dear Complaints Manager,

RE: Formal Complaint — Unauthorised Transaction & Failure to Refund

I am writing to formally lodge a complaint regarding an unauthorised transaction of $1,247.50 debited from my account (Account No: 062-001 1234 5678) on 14 March 2026, which I did not authorise.

I immediately contacted your customer service on 15 March 2026 and was advised a dispute had been lodged (Reference: CBA-2026-44821). Despite your organisation's commitment to resolve disputes within 21 days, I am yet to receive any substantive response or refund as of the date of this letter.

Under the Australian Banking Code of Practice and the ePayments Code, I am entitled to a full refund of this unauthorised transaction. I request that Commonwealth Bank:

1. Immediately refund the full amount of $1,247.50 to my account;
2. Provide written confirmation of the refund within 5 business days;
3. Confirm the security measures taken to prevent recurrence.

Should I not receive a satisfactory resolution within 21 days from the date of this letter, I will have no choice but to escalate this matter to the Australian Financial Complaints Authority (AFCA).

Yours sincerely,

Jane Smith
123 Example Street, Parramatta NSW 2150
jane.smith@email.com | 0400 000 000
Date: 16 June 2026`,
    locked_features: ["2nd & 3rd Complaint Letters", "Escalation Letter to AFCA", "Accept/Deny Offer Letters", "Full Tribunal Bundle PDF"]
  },
  {
    tier: "Pro",
    price: "$35.00/mo",
    color: "#FFD700",
    icon: Zap,
    popular: true,
    description: "See the full 5-letter suite for a telco dispute — from 1st complaint to escalation to TIO.",
    letter_title: "Escalation Letter to TIO — Telco",
    letter: `To the Telecommunications Industry Ombudsman
PO Box 276, Collins Street West VIC 8007

Dear TIO Case Officer,

RE: Escalation of Unresolved Dispute — Telstra Corporation — Account No: 0412 345 678

I am writing to formally escalate my dispute with Telstra Corporation to the Telecommunications Industry Ombudsman (TIO), having exhausted all internal complaint processes without satisfactory resolution.

BACKGROUND
On 2 January 2026, Telstra applied an erroneous $340.00 international roaming charge to my account despite my having purchased and activated an international roaming pack prior to travel. I contacted Telstra on three separate occasions (2 Jan, 15 Jan, and 3 Feb 2026) and submitted two formal written complaints. Each time I was advised the matter was "under review."

TELSTRA'S RESPONSE
Telstra's final response dated 10 March 2026 (Ref: TLS-2026-98234) offered a goodwill credit of $50.00, which I rejected as inadequate given the erroneous charge was $340.00 and caused direct financial hardship.

WHAT I AM SEEKING
1. Full reversal of the $340.00 erroneous charge;
2. Compensation of $150.00 for time and inconvenience;
3. Formal written apology.

I have enclosed copies of all correspondence, account statements, and my international roaming pack activation confirmation.

Yours faithfully,

Michael Johnson
45 Sample Road, Chatswood NSW 2067
michael.j@email.com | 0455 111 222
Date: 16 June 2026`,
    locked_features: ["Accept Offer Letter", "Deny Offer Letter", "Chaos Score analytics", "ZIP bundle export"]
  },
  {
    tier: "Command",
    price: "$49.00/mo",
    color: "#EF4444",
    icon: Shield,
    description: "The complete 6-letter escalation bundle with Chaos Score and full tribunal-ready PDF pack.",
    letter_title: "Accept Settlement Offer Letter — Insurance",
    letter: `To the Claims Manager,
Allianz Australia Insurance Limited
GPO Box 4049, Sydney NSW 2001

RE: Acceptance of Settlement Offer — Claim No: ALZ-2026-77321
Your Reference: Settlement Offer Letter dated 5 June 2026

Dear Claims Manager,

I write in response to your settlement offer of $18,500.00 in full and final resolution of my home contents claim (Claim No: ALZ-2026-77321) lodged on 14 February 2026 following a burglary at my property.

After careful consideration, and without prejudice to my rights under the Insurance Contracts Act 1984 (Cth), I accept the offered amount of $18,500.00 in full and final settlement of this claim on the following conditions:

1. Payment is made within 10 business days of this letter;
2. Allianz provides written confirmation that the claim is fully settled and no further action will be taken to recover any portion of the settlement;
3. My policy remains in force and no adverse notation is made against my claims history.

Please arrange for the funds to be transferred to my nominated bank account (BSB: 062-001, Account: 9876 5432) and forward the settlement deed for my execution.

I trust this brings the matter to a satisfactory conclusion.

Yours sincerely,

Sarah Williams
78 Test Avenue, Penrith NSW 2750
sarah.w@email.com | 0422 333 444
Date: 16 June 2026`,
    locked_features: []
  }
];

export default function SamplePreviews() {
  const navigate = useNavigate();
  const [activeTier, setActiveTier] = useState(0);

  const sample = TIER_SAMPLES[activeTier];
  const Icon = sample.icon;

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <div className="max-w-5xl mx-auto px-4 py-8">
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="text-white hover:bg-gray-800">
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div>
            <h1 className="text-2xl sm:text-3xl font-display font-bold text-white">Sample Previews</h1>
            <p className="text-gray-400 mt-1 text-sm">See real examples of what each plan generates for you.</p>
          </div>
        </div>

        {/* Tier Selector */}
        <div className="grid sm:grid-cols-3 gap-4 mb-8">
          {TIER_SAMPLES.map((t, i) => {
            const TIcon = t.icon;
            return (
              <motion.button
                key={t.tier}
                onClick={() => setActiveTier(i)}
                whileTap={{ scale: 0.97 }}
                className={`relative rounded-xl border-2 p-4 text-left transition-all ${activeTier === i ? "border-[#FFD700] bg-[#FFD700]/10" : "border-gray-800 hover:border-gray-600 bg-gray-900"}`}
              >
                {t.popular && (
                  <Badge className="absolute -top-2 left-3 bg-[#FFD700] text-black font-bold text-xs">POPULAR</Badge>
                )}
                <div className="flex items-center gap-3 mb-2">
                  <TIcon className="w-5 h-5" style={{ color: t.color }} />
                  <span className="font-bold text-white">{t.tier}</span>
                </div>
                <p className="text-sm font-bold" style={{ color: t.color }}>{t.price}</p>
                <p className="text-xs text-gray-400 mt-1">{t.description}</p>
              </motion.button>
            );
          })}
        </div>

        {/* Letter Preview */}
        <motion.div
          key={activeTier}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="bg-white rounded-2xl overflow-hidden shadow-2xl mb-8"
        >
          {/* Letter Header Banner */}
          <div className="px-6 py-4 flex items-center gap-3" style={{ backgroundColor: sample.color }}>
            <Icon className="w-5 h-5 text-white" />
            <div>
              <p className="font-bold text-white text-sm">{sample.tier} Plan — Sample Document</p>
              <p className="text-white/80 text-xs">{sample.letter_title}</p>
            </div>
          </div>

          {/* Letter Body */}
          <div className="p-6 sm:p-10">
            <div className="flex justify-between items-start mb-6">
              <div>
                <p className="text-2xl font-black text-black" style={{ fontFamily: "Times New Roman, serif" }}>CHAOS CONTROLLER™</p>
                <p className="text-xs text-gray-500">Consumer Advocacy Platform</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-gray-400">SAMPLE DOCUMENT</p>
                <p className="text-xs text-gray-400">Generated: 16 June 2026</p>
              </div>
            </div>
            <hr className="border-gray-300 mb-6" />
            <pre className="whitespace-pre-wrap text-sm text-gray-800 leading-relaxed" style={{ fontFamily: "Times New Roman, serif" }}>
              {sample.letter}
            </pre>
          </div>
        </motion.div>

        {/* Locked Features */}
        {sample.locked_features.length > 0 && (
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-5 mb-8">
            <p className="font-bold text-white mb-3 flex items-center gap-2">
              <Lock className="w-4 h-4 text-gray-400" /> Also included in higher tiers:
            </p>
            <div className="grid sm:grid-cols-2 gap-2">
              {sample.locked_features.map(f => (
                <div key={f} className="flex items-center gap-2 text-sm text-gray-400">
                  <Lock className="w-3.5 h-3.5 text-gray-600 shrink-0" />
                  {f}
                </div>
              ))}
            </div>
          </div>
        )}

        {sample.locked_features.length === 0 && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-5 mb-8 flex items-center gap-3">
            <Star className="w-5 h-5 text-red-400 shrink-0" />
            <p className="text-white font-bold">Command plan includes everything — all 6 letters, full PDF bundle, Chaos Score, and ZIP export.</p>
          </div>
        )}

        {/* CTA */}
        <div className="bg-[#FFD700]/10 border border-[#FFD700]/30 rounded-xl p-6 text-center">
          <h3 className="text-xl font-display font-bold text-white mb-2">Ready to fight back?</h3>
          <p className="text-gray-400 text-sm mb-4">Get started with your first case today — pay via PayID in minutes.</p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Button
              className="bg-[#FFD700] hover:bg-[#FFD700]/90 text-black font-bold px-8"
              onClick={() => navigate("/payments")}
            >
              View Plans & Pay
            </Button>
            <Button
              variant="outline"
              className="border-gray-600 text-white hover:bg-gray-800"
              onClick={() => navigate("/register")}
            >
              Create Free Account
            </Button>
          </div>
        </div>

        {/* Footer */}
        <p className="text-center text-gray-600 text-xs mt-8">
          Designed & Developed by Deb King, Glenmore Park 2025
        </p>
      </div>
    </div>
  );
}