import React from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Scale, ArrowLeft } from "lucide-react";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="bg-card border-b border-border sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex items-center gap-4 mb-4">
            <Button variant="outline" size="icon" onClick={() => navigate(-1)}>
              <ArrowLeft className="w-4 h-4" />
            </Button>
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Scale className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h1 className="font-heading font-bold text-2xl text-foreground">Terms & Conditions</h1>
                <p className="text-sm text-muted-foreground mt-1">Last updated: 15 June 2026</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">1. Acceptance of Terms</h2>
          <p className="text-foreground leading-relaxed">
            By accessing and using Chaos Controller ("the Platform"), you accept and agree to be bound by the terms 
            and provision of this agreement. If you do not agree to abide by these terms, please do not use this Platform.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">2. Service Description</h2>
          <p className="text-foreground leading-relaxed">
            Chaos Controller is a consumer advocacy and dispute management platform that provides:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Case management tools for consumer disputes</li>
            <li>AI-powered complaint letter generation</li>
            <li>Evidence organisation and document management</li>
            <li>Timeline tracking and deadline management</li>
            <li>Escalation bundle preparation for tribunals</li>
            <li>Access to complaint contact directories</li>
          </ul>
          <p className="text-foreground leading-relaxed mt-4">
            The Platform does not provide legal advice. All content generated by the Platform should be reviewed 
            by the user before use.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">3. User Responsibilities</h2>
          <p className="text-foreground leading-relaxed">
            You agree to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Provide accurate and complete information when creating cases</li>
            <li>Review all AI-generated content before sending to third parties</li>
            <li>Maintain the confidentiality of your account credentials</li>
            <li>Not use the Platform for any unlawful purpose</li>
            <li>Not impersonate any person or entity</li>
            <li>Not upload malicious code or attempt to breach Platform security</li>
          </ul>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">4. AI-Generated Content</h2>
          <p className="text-foreground leading-relaxed">
            The Platform uses artificial intelligence to generate complaint letters and extract data from documents. 
            You acknowledge that:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>AI-generated content may contain errors or inaccuracies</li>
            <li>You are responsible for reviewing all generated content before use</li>
            <li>The Platform does not guarantee the accuracy or completeness of AI output</li>
            <li>You should verify all facts, dates, and claims before submitting complaints</li>
          </ul>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">5. No Legal Advice</h2>
          <p className="text-foreground leading-relaxed">
            Chaos Controller is not a law firm and does not provide legal advice. The Platform provides 
            administrative and organisational tools to help you manage consumer disputes. For legal advice, 
            you should consult with a qualified legal practitioner.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">6. Data and Privacy</h2>
          <p className="text-foreground leading-relaxed">
            Your use of the Platform is also governed by our Privacy Policy. By using the Platform, you consent 
            to the collection and use of information as outlined in the Privacy Policy.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">7. Intellectual Property</h2>
          <p className="text-foreground leading-relaxed">
            All content, features, and functionality of the Platform, including but not limited to text, graphics, 
            logos, and software, are the exclusive property of Chaos Controller and are protected by copyright, 
            trademark, and other intellectual property laws.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">8. Limitation of Liability</h2>
          <p className="text-foreground leading-relaxed">
            To the maximum extent permitted by law, Chaos Controller shall not be liable for any indirect, 
            incidental, special, consequential, or punitive damages arising from your use of the Platform, 
            including but not limited to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-foreground ml-4">
            <li>Loss of profits, data, or business opportunities</li>
            <li>Unsuccessful dispute outcomes</li>
            <li>Errors or omissions in AI-generated content</li>
            <li>Service interruptions or data loss</li>
          </ul>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">9. Modifications to Service</h2>
          <p className="text-foreground leading-relaxed">
            Chaos Controller reserves the right to modify, suspend, or discontinue any part of the Platform 
            at any time without prior notice. We shall not be liable to you or any third party for any 
            modification, suspension, or discontinuance of the service.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">10. Termination</h2>
          <p className="text-foreground leading-relaxed">
            We may terminate or suspend your access to the Platform immediately, without prior notice or 
            liability, for any reason, including breach of these Terms. Upon termination, your right to use 
            the Platform will immediately cease.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">11. Governing Law</h2>
          <p className="text-foreground leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of Australia, 
            without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="prose prose-sm max-w-none">
          <h2 className="font-heading font-bold text-xl text-foreground mb-4">12. Contact Information</h2>
          <p className="text-foreground leading-relaxed">
            For questions about these Terms & Conditions, please contact us at:
          </p>
          <div className="bg-secondary/30 border border-border rounded-lg p-4 mt-4">
            <p className="text-foreground font-medium">Chaos Controller</p>
            <p className="text-foreground">Email: chaoscontrollerapp@gmail.com</p>
            <p className="text-foreground">Website: app.base44.com/6a2ac3b012e45642b1f94671</p>
            <p className="text-foreground">Phone: 0413 572 850</p>
          </div>
        </section>

        {/* Acceptance Button */}
        <div className="border-t border-border pt-8 mt-8">
          <Button 
            onClick={() => navigate("/")}
            className="w-full gap-2"
          >
            <Scale className="w-4 h-4" />
            I Accept the Terms & Conditions
          </Button>
        </div>
      </div>
    </div>
  );
}